### ISSUE TITLE
Basic stack deployment documentation - no availability domains available

### ISSUE THREAD

**Issue by gvenzl** [oracle-quickstart/oci-cloudnative#102]
Hi,

When running through the basic deployment steps, I noticed that there is a step `4.iii: Availability Domain - Select any availability domain to create the resources. If you run in to service limits, you could try another availability domain.`

There is 1) a type in the word `into` and 2) there are no availability domains to chose from for the Free Tier.

**Comment by mvandervliet** [comment]
Thanks @gvenzl. You're right, these instructions are no longer applicable because the stack is able to auto-determine the appropriate Always Free availability domain (assuming resource limits not exceeded)
