### ISSUE TITLE
Support multi-line version files

### ISSUE THREAD

**Issue by peterj** [oracle-quickstart/oci-cloudnative#121]
Certain services support a --build-arg version=<version> used to embed the version (tag) in formation within the build. This presents a use case where the same source code can be used to build other tags in addition to the semver (think svc mesh). In the case of storefront, we might wish to support a multi-line VERSION file with contents like:
```
2.1.1
2.2.0-beta
```

**Comment by jeevanjoseph** [comment]
@peterj  - close this ?

**Comment by peterj** [comment]
Up to @mvandervliet, but I don't think it makes much sense to do this.

**Comment by mvandervliet** [comment]
I propose we leave it open until there's an alternate solution. Fair?

**Comment by junior** [comment]
Setting to close this. No use case appeared where the same code could have two different versions. If there's a code change, the old version tag should not be valid. Beta version should be used in a separate branch from master/main, in that case, just use the new version to push to docker registry.

**Comment by junior** [comment]
@mvandervliet any comments before gets closed?

**Comment by mvandervliet** [comment]
> @mvandervliet any comments before gets closed?

no, that's ok by me
