### ISSUE TITLE
Stream and shipping charts are missing in the new release

### ISSUE THREAD

**Issue by ahsalman84** [oracle-quickstart/oci-cloudnative#128]
under "/mushop/deploy/complete/helm-chart/mushop/charts/", there was two more charts, stream and shipping, currently they are missing which make the lab 6 in "https://slides.mushop.ateam.cloud/#/agenda" not running properly as the corresponding pods for these two pods no created..

**Comment by mvandervliet** [comment]
Thanks @ahsalman84 - the workshop materials are in the process of being upgraded to reflect the recent changes. You'll notice that the official docs show these services removed already: https://oracle-quickstart.github.io/oci-cloudnative/#mushop-services. Will leave issue open until the labs are updated.

**Comment by ahsalman84** [comment]
Thanks @mvandervliet for your reply, 
Till we have the updated workshop material, could you please share with me the commands to test the messaging queuing to the OSS, similar to what we had in the workshop labs

**Comment by mvandervliet** [comment]
The workshop has been updated. Find the new streaming content in the agenda slide above.

**Comment by ahsalman84** [comment]
Streaming page is not working, getting "404 Not Found"

**Comment by mvandervliet** [comment]
Apologies, the shipping content was renamed to streaming: https://slides.mushop.ateam.cloud/workshop/streaming.html

You may need to refresh your browser to see changes in the agenda

**Comment by ahsalman84** [comment]
It is working now, many thanks
