### ISSUE TITLE
Standardize the method to configure TNS ENV.

### ISSUE THREAD

**Issue by jeevanjoseph** [oracle-quickstart/oci-cloudnative#133]
The java applications use an environment variable TNS_ENV to determine the ojdbc configuration.
Currently this is an environment var on the container, that is set through the helm chart (default value set by chart, can be overridden). 
This is to track where to make this configurable (helm chart or elsewhere)

**Comment by peterj** [comment]
Move the TNS_ENV to the Dockerfile and remove it from Helm.
