### ISSUE TITLE
Getting "Authorization failed or requested resource not found"} when Calling the API

### ISSUE THREAD

**Issue by ahsalman84** [oracle-quickstart/oci-cloudnative#134]
Hi,

I'm getting the below error when calling my API " curl -X POST -d '{"email": "youremail@example.com"}'  https://aaa.apigateway.us-ashburn-1.oci.customer-oci.com/newsletter/subscribe "

Error:
{"code":"NotAuthorizedOrNotFound","message":"Authorization failed or requested resource not found"}[

I have created the required polices to use functions and i believe everything is set according to the workshop lab

Thanks,
Ahmad

**Comment by mvandervliet** [comment]
As a sanity check, did you replace the APIGW endpoint URL in the docs with the unique one issued when yours was provisioned?

**Comment by ahsalman84** [comment]
Yes already replaced, and i rechecked my policies as well in case is missed anything but still the same

Do i need to do anything with the DNS? i just created a dummy approved sender and used it for the fnc configuration

**Comment by peterj** [comment]
There’s nothing you need to do in terms of the DNS. Is there anything in
the api gateway logs?

**Comment by peterj** [comment]
@ahsalman84 can you provide more logs?

**Comment by jeevanjoseph** [comment]
@ahsalman84 - any update on the logs ?

**Comment by jeevanjoseph** [comment]
@ahsalman84 bump !
