### ISSUE TITLE
File Size Cannot Be Larger than 11mb

### ISSUE THREAD

**Issue by anthealy** [oracle-quickstart/oci-cloudnative#135]
The current file size is 12.6mb, max allowed in the console is 11mb.  
![Screenshot 2020-03-09 at 10 38 01](https://user-images.githubusercontent.com/33655905/76213210-1a5d4c00-6202-11ea-99ca-bd5b87f3f18c.png)

**Comment by mvandervliet** [comment]
Hi @anthealy - how did you create the stack to upload? I looks like the whole repo was uploaded. Generally there are two options for the ORM stack:

1. Use the [mushop-basic-stack-vX.X.X.zip](https://github.com/oracle-quickstart/oci-cloudnative/releases/tag/v1.1.0) from releases.
1. Build your own stack from the repo following these [instructions](https://github.com/oracle-quickstart/oci-cloudnative/tree/v1.1.0/deploy/basic#build)

**Comment by junior** [comment]
@anthealy we do not support download the repo and upload as stack.

**Comment by anthealy** [comment]
I downloaded Stack from here:   https://github.com/oracle-quickstart/oci-cloudnative

as per Oracle Documentation: https://docs.cloud.oracle.com/en-us/iaas/Content/FreeTier/freetier.htm

**Comment by anthealy** [comment]
I tried https://github.com/oracle-quickstart/oci-cloudnative/releases/download/v1.1.0/mushop-basic-stack-v1.1.0.zip and it worked fine.. thanks for your help.
