### ISSUE TITLE
Assets init fail when Istio proxy is injected 

### ISSUE THREAD

**Issue by peterj** [oracle-quickstart/oci-cloudnative#147]
Looks like the istio proxy is blocking catalogue init container from populating the object storage.

**Comment by junior** [comment]
catalogue does not populate the object storage, this is done by the assets job.

The jobs may need to use the tag `sidecar.isitio.io/inject: "false" ` or have a script to quitquitquit the sidecar for completed jobs.

**Comment by junior** [comment]
This is probably also affecting the carts, catalogue, assets, users and orders. All have jobs.

**Comment by peterj** [comment]
yep, will make changes to other yamls as well.
