### ISSUE TITLE
Enable Kubernetes Dashboard post deployment

### ISSUE THREAD

**Issue by amartellone** [oracle-quickstart/oci-cloudnative#164]
Hi,
I've tried to enable,post-deployment, the Kubernetes Dashboard, but it doesn't work. The only way is to check the CLUSTER_OPTIONS_ADD_ONS_IS_KUBERNETES_DASHBOARD_ENABLED during the play of the terraform script? Is there a way to enable this option by CLI post deployment? 
Many thanks

**Comment by junior** [comment]
@amartellone you enable the Kubernetes Dashboard post installation doing the regular deployment. The option `CLUSTER_OPTIONS_ADD_ONS_IS_KUBERNETES_DASHBOARD_ENABLED ` is just a helper.


To deploy the Kubernetes Dashboard, please follow the steps on the official page here: https://kubernetes.github.io/dashboard/

To get access, you will need a Service Account. You can follow these steps to do that: https://docs.cloud.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengstartingk8sdashboard.htm




Optionally, you can deploy the Kubernetes Dashboard using Helm chart. You can find the details here: https://github.com/kubernetes/dashboard/tree/master/aio/deploy/helm-chart/kubernetes-dashboard

**Comment by amartellone** [comment]
Thanks Junior. It works.
