### ISSUE TITLE
Default ATP credentials

### ISSUE THREAD

**Issue by amartellone** [oracle-quickstart/oci-cloudnative#167]
Hi,

I am not able to get the default admin credentials for the ATP database? Is there a way to get it?

Regards

**Comment by junior** [comment]
You can execute the command: 
```
terraform output autonomous_database_password
```

Or check on the terraform state.

**Comment by junior** [comment]
@amartellone Did you get the admin db password?

**Comment by jeevanjoseph** [comment]
@junior Should we consider adding it back to the outputs in the app info ? Its not really any less secure than what it is today, and its a demo after all ?

**Comment by junior** [comment]
Yeah, same with Grafana admin credentials. @amartellone help me figure out that. I'm including on the next PR.

**Comment by junior** [comment]
@amartellone, were you able to get and use the ATP admin password?

**Comment by amartellone** [comment]
@junior Yes! Thanks a lot for your support. I'm going to close the issue.
