### ISSUE TITLE
Error: Invalid index on main.tf line 13

### ISSUE THREAD

**Issue by stefankoser** [oracle-quickstart/oci-cloudnative#170]
I have tried to install mushop basic in one tenancy in Frankfurt. Here is the terraform log:

2020/06/11 14:43:52[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:43:52[TERRAFORM_CONSOLE] [INFO] Initializing provider plugins...
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] The following providers do not have any version constraints in configuration,
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] so the latest version was installed.
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] To prevent automatic upgrades to new major versions that may contain breaking
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] changes, it is recommended to add version = "..." constraints to the
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] corresponding provider blocks in configuration, with the constraint strings
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] suggested below.
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] * provider.oci: version = "~> 3.80"
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] * provider.random: version = "~> 2.1"
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] * provider.template: version = "~> 2.1"
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] Terraform has been successfully initialized!
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] You may now begin working with Terraform. Try running "terraform plan" to see
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] any changes that are required for your infrastructure. All Terraform commands
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] should now work.
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] If you ever set or change modules or backend configuration for Terraform,
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] rerun this command to reinitialize your working directory. If you forget, other
2020/06/11 14:43:53[TERRAFORM_CONSOLE] [INFO] commands will detect it and remind you to do so if necessary.
2020/06/11 14:43:57[TERRAFORM_CONSOLE] [INFO] data.template_file.mushop: Refreshing state...
2020/06/11 14:43:57[TERRAFORM_CONSOLE] [INFO] data.oci_identity_availability_domains.ADs: Refreshing state...
2020/06/11 14:43:57[TERRAFORM_CONSOLE] [INFO] data.oci_objectstorage_namespace.user_namespace: Refreshing state...
2020/06/11 14:43:57[TERRAFORM_CONSOLE] [INFO] data.oci_limits_services.test_services: Refreshing state...
2020/06/11 14:43:58[TERRAFORM_CONSOLE] [INFO] data.oci_limits_limit_values.test_limit_values[1]: Refreshing state...
2020/06/11 14:43:58[TERRAFORM_CONSOLE] [INFO] data.oci_limits_limit_values.test_limit_values[2]: Refreshing state...
2020/06/11 14:43:58[TERRAFORM_CONSOLE] [INFO] data.oci_limits_limit_values.test_limit_values[0]: Refreshing state...
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] Error: Invalid index
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]   on main.tf line 13, in resource "oci_core_instance" "app-instance":
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]   13:   availability_domain = local.availability_domain[0]
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]     |----------------
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]     | local.availability_domain is empty tuple
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] The given key does not identify an element in this collection value.
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] Error: Invalid index
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]   on main.tf line 13, in resource "oci_core_instance" "app-instance":
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]   13:   availability_domain = local.availability_domain[0]
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]     |----------------
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]     | local.availability_domain is empty tuple
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] The given key does not identify an element in this collection value.
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO] 
2020/06/11 14:44:00[TERRAFORM_CONSOLE] [INFO]

**Comment by junior** [comment]
The MuShop Basic was designed to only work with the Always-Free resources. Always-free resources are only available on the Home Region of your tenancy.

If you try to install in a tenancy that does not have these resources, you will receive this kind of error.

Are you installing on a tenancy where the home region is Frankfurt and there are Always-free resources (LB, ATP and Compute) available?


You also have an option to deploy the MuShop Complete, which does not use Always-free resources. You can find here: https://github.com/oracle-quickstart/oci-cloudnative/releases/download/v2.0.0/mushop-stack-v2.0.0.zip

**Comment by jeevanjoseph** [comment]
We can consider expanding the scope to include non-free as well, although we should propbabaly create a new stack for that, and split this completely from the container native effort.

**Comment by junior** [comment]
> We can consider expanding the scope to include non-free as well, although we should probably create a new stack for that, and split this completely from the container native effort.

This issue is related to the full mushop stack, there's no use of always free resources.

**Comment by junior** [comment]
@stefankoser you where able to install on a fresh tenancy or on a tenancy that has Always-free resources on the home region?
