### ISSUE TITLE
Error creating Autonomous Database 18c

### ISSUE THREAD

**Issue by CarlosMartinMartinez** [oracle-quickstart/oci-cloudnative#182]
Hi!

My name is Carlos and I'm a Solutions Engineer at Oracle. Recently I've been working with a customer who had issues running this script. After a month of debugging with Oracle Support and Product, it came down to something as simple like updating the script to force the version of the DB to be 19c since 18c is no longer available for Always Free ATPs (at least in Frankfurt).

Since new users of OCI can follow a simple wizard to download this and create a stack in Resource Manager without being expected to get into the script itself, could you update this on Github?

**Comment by junior** [comment]
Scripts have been updated already. You can find the v1.1.2 pre-release under the /releases.

The PR #181 will also include the change to support the new regions (And any new that come up).

This PR also will update the README with the new stack.

**Comment by junior** [comment]
Please, download the new stack with the updated from here: https://github.com/oracle-quickstart/oci-cloudnative/releases/download/v1.1.3/mushop-basic-stack-v1.1.3.zip

**Comment by CarlosMartinMartinez** [comment]
Thank you very much Adao! 
What the version when OCI users select it directly when creating a new Stack rather than downloading and uploading the zip file? Who is responsible for updating that? :)

**Comment by jeevanjoseph** [comment]
@CarlosMartinMartinez - if you mean the "solution hub" in resource manager, we are haivng that updated as well. In that case we want to ensure that the solution you get from the solution hub is always the latest that we publish. 

This being said, 
> After a month of debugging with Oracle Support and Product...
If you have issue with the stack, please raise an issue here. This is an open source sample and is not covered by support or product (unless you are referring to the solutions hub).

**Comment by junior** [comment]
OCI Console and Solution Hub is getting updated.

**Comment by jeevanjoseph** [comment]
tagging #155 and #177

**Comment by junior** [comment]
Issue fixed with new stack: https://github.com/oracle-quickstart/oci-cloudnative/releases/download/v1.1.3/mushop-basic-stack-v1.1.3.zip
