### ISSUE TITLE
Basic stack deployment fails in HYD region

### ISSUE THREAD

**Issue by sthatiko** [oracle-quickstart/oci-cloudnative#203]
Created a stack with latest mushop basic zip and applied. Failed with below error.

`Error: Invalid index
  on main.tf line 14, in resource "oci_core_instance" "app_instance" 
  14:   availability_domain = local.availability_domain[0]
    |----------------
    | local.availability_domain is empty tuple
The given key does not identify an element in this collection value.
Error: Invalid index
  on main.tf line 14, in resource "oci_core_instance" "app_instance" 
  14:   availability_domain = local.availability_domain[0]
    |----------------
    | local.availability_domain is empty tuple
The given key does not identify an element in this collection value.`

**Comment by junior** [comment]
@sthatiko this error happen when you do not have the resources available on your region. Currently you can only use Always-free eligible resources, which is only available on your home region. A new version of the mushop basic stack will be released tomorrow, and will allow you change the shapes.

HYD is your home region?

**Comment by sthatiko** [comment]
My home region is phoenix. I am trying to deploy free tier eligible stack.

**Comment by junior** [comment]
"You must create the Always Free Compute instances in your home region."

As referenced here: https://docs.cloud.oracle.com/en-us/iaas/Content/FreeTier/resourceref.htm

The next mushop basic release will allow you use other shapes (not only always-free) that are available on other regions as well.

**Comment by junior** [comment]
@sthatiko The new release of the mushop (PR  #200) automatically use the home region when deploying using Always-free eligible resources, also checks if you have enough limit to use.

You can also select the advanced options and change the shapes to allow you use any shape available.

Can be download from here: https://github.com/oracle-quickstart/oci-cloudnative/releases/download/v1.2.0/mushop-basic-stack-v1.2.0.zip

Let me know if this works for you.
