### ISSUE TITLE
Error: Invalid function argument

### ISSUE THREAD

**Issue by youssef50** [oracle-quickstart/oci-cloudnative#210]
Info:
------
Using deploy/basic folder.

# terraform -version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/oci v3.93.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0

Issue:
------
- Successfully ran the initial terraform apply and everything went fine.
- Tried to update a resource and getting below error message

Error: Invalid function argument

  on datasources.tf line 92, in locals:
  92:   file("ERROR: No limits available for the chosen compute shape and number of nodes")) : 0

Invalid value for "path" parameter: no file exists at ERROR: No limits
available for the chosen compute shape and number of nodes; this function
works only with files that are distributed as part of the configuration source
code, so if this file will be created by a resource in this configuration you
must instead obtain this result from an attribute of that resource.

**Comment by junior** [comment]
@youssef50 That test means that you do not have enough limit for the shape that you requested. Which resource that you request change?

Remember that if you are using 2 compute shape and is increasing or decreasing the number of node, you still need all the shapes limit before complete all tasks.

**Comment by youssef50** [comment]
The same error message is also displayed when during terraform destroy, using "mushop-basic-stack-latest as of oct1-2020"

Error: Error in function call
  on datasources.tf line 92, in locals:
  92:   file(   "ERROR: No limits available for the chosen compute shape and number of nodes")   ) : 0
Call to function "file" failed: no file exists at ERROR: No limits available
for the chosen compute shape and number of nodes.

**Comment by junior** [comment]
The error probably happen on the same tenancy that you do not have always-free eligible compute shapes.

Note that you can change the shape on the mushop basic stack that you are using. Just click on the advanced options and change the shape to one that you have limit on your tenancy/region.

**Comment by junior** [comment]
P.S.: This "error" is forced to test the limit, as the terraform 0.12 does not offer any conditional message functions to stop the execution if a condition is not meet
