### ISSUE TITLE
Navigating through left sided menu wont work

### ISSUE THREAD

**Issue by paschalidi** [oracle-quickstart/oci-cloudnative#228]
Hey 👋  Short UI issue. 

Looks like this part of the ui isnt responding. Clicking wont prompt me to a new url.
![image](https://user-images.githubusercontent.com/4181674/103148604-dff97700-4761-11eb-8afc-ea7e1737f593.png)

Perhaps you would like to have a look. Also happy to contribute on that part. 

_PS. great project everyone! Thanks!_

**Comment by mvandervliet** [comment]
Thanks @paschalidi. Will have a look. What is your browser/version?

**Comment by paschalidi** [comment]
Hey @mvandervliet 
I am using  Google Chrome 
```
Version 87.0.4280.88 (Official Build) (x86_64)
```
