### ISSUE TITLE
Getting a limit error when applying terraform stack for the basic deployment

### ISSUE THREAD

**Issue by paschalidi** [oracle-quickstart/oci-cloudnative#230]
Getting an error when applying the basic stack on oracle cloud. The error I am getting is the following. 
```
Error: Service error:LimitExceeded. The following service limits were exceeded: lb-10mbps-micro-count. Request a service limit increase from the service limits page in the console. . http status code: 400. Opc request id: 909fadbbb8ff3c5736c6a5fdda6ccb2d/2F47818081BF58BBAF2764549CDB9646/15C7DE2334B852C0CCEBD180B321EABC
  on loadbalancer.tf line 5, in resource "oci_load_balancer_load_balancer" "mushop_lb" 
   5: resource "oci_load_balancer_load_balancer" "mushop_lb" {
```

Any resources on how I could solve this?

**Comment by junior** [comment]
@paschalidi The stack tests if you have limit available of the resource that you want to deploy. The standard is using Always-free resources. 

That message is showing that you do not have the 10mbps-micro shape for Loadbalancer. You may be already using it or trying to apply on a tenancy that does not have Always-free resources available.

You can check what shapes are available for you using the OCI console > Governance and Administration >Governance > Limits, Quotas & Usage and check the LB shapes available.

Note that you can select the advance mode on the stack and change the shape of the load balancer to be deployed. Same for the Compute and ATP.

**Comment by jeevanjoseph** [comment]
@paschalidi - were you able to get a limit increase ? I’m closing this since this is something that this project cannot address.

**Comment by fragre77** [comment]
I had the same issue.
It seems that **flexible** is the load balancer shape to use with **Always Free resources** now (I'm using Germany Central (Frankfurt) region). 
So I modified the value of **lb_shape** in **variables.tf** to 'flexible'

variable "lb_shape" {
  default = "flexible"
}

and I added **shape_details** (which is required if you choose the 'flexible' shape) in **loadbalancer.tf**

resource "oci_load_balancer_load_balancer" "mushop_lb" {
  compartment_id = (var.lb_compartment_ocid != "") ? var.lb_compartment_ocid : var.compartment_ocid
  display_name   = "mushop-${random_string.deploy_id.result}"
  shape          = var.lb_shape
  subnet_ids     = [oci_core_subnet.mushop_lb_subnet.id]
  is_private     = "false"
  freeform_tags  = local.common_tags

  shape_details {
	maximum_bandwidth_in_mbps = 10
        minimum_bandwidth_in_mbps = 10
      }
}

After these changes I could apply the stack successfully.
Hope this helps!

regards
