### ISSUE TITLE
lb_shape error for free basic deployment

### ISSUE THREAD

**Issue by tuxerrante** [oracle-quickstart/oci-cloudnative#237]
Hi,
I'm trying to deploy the basic version as explained [here ](https://github.com/oracle-quickstart/oci-cloudnative#Getting-Started-with-MuShop-Basic)in the Readme, and in the Architecture Center (https://docs.oracle.com/en/solutions/cloud-native-ecommerce/index.html),
but I get this error:
"the following service limits were exceeded: lb-10mbps-micro-count."
I do not have other load balancers.

Is the TF plan to be updated or maybe I have some hidden resource?
Thanks

Here the logs: https://gist.github.com/tuxerrante/f17520ae3cc60eb259de1a5a82bdb8c8

**Comment by junior** [comment]
@tuxerrante, which stack are you using? The https://docs.oracle.com/en/solutions/cloud-native-ecommerce/index.html points to the Complete stack, which uses the OKE and deploys on Kubernetes.

The logs that you posted are from the Basic stack, that deploys a monolith on the compute.

For the basic, if you have always free resources, should show on your limits page, on the OCI console, on your Home Region. Something like this: 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/551007/108746134-89aa7980-7501-11eb-815c-7c3bb3e38f42.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/551007/108746244-af378300-7501-11eb-8a31-1c25721b26ef.png">

**Comment by tuxerrante** [comment]
Hi,
I've downloaded the mushop-basic-stack-latest.zip from the Readme [link](https://github.com/oracle-quickstart/oci-cloudnative/releases/latest/download/mushop-basic-stack-latest.zip), to deploy the basic setup.

I have a free tier and I should have access to one public load balancer:
![image](https://user-images.githubusercontent.com/8364469/108747530-d14ef680-753d-11eb-974e-b0b6fe0e9e2b.png)

**Comment by junior** [comment]
This is a new standard tenancy? the 10Mbps Always Free Load Balancer for you shows 0 service limit. You only have Flexible LB.

The mushop-basic-stack allows you select "Advanced Options" to change the shapes for Compute, LB and ATP DB. I'm planning to release an option for Flexible LB soon.

**Comment by tuxerrante** [comment]
In this tenancy the free trial period is expired, but as per my
understanding these resources should be "always free".

Let me know if I can contribute in some way, I will be happy to do it.

Thanks

Il Lun 22 Feb 2021, 21:10 Adao Junior <notifications@github.com> ha scritto:

**Comment by junior** [comment]
@tuxerrante a new version of the basic stack have been created, supporting the flexible load balancer on the new tenancies with Always-free resources. The new version will be published tomorrow. If you want sneak peak, attached the new mushop basic stack.
[mushop-basic-stack-v1.2.1.zip](https://github.com/oracle-quickstart/oci-cloudnative/files/6026858/mushop-basic-stack-v1.2.1.zip)

**Comment by tuxerrante** [comment]
That seemed to work! :) 

Maybe the FAQ could be extended with these questions:
- How could I add the two VM in a instance pool from TF? 
- How to read the plans? Where to start modifying bash scripts?
- Load balancer backend set health is Unknown

Thanks again

**Comment by junior** [comment]
@tuxerrante :

> Maybe the FAQ could be extended with these questions:
> 
> * How could I add the two VM in a instance pool from TF?

Can you elaborate more? You are looking for instructions to create an Instance Configuration, then a Instance Pool, and use the VMs from that pool?

> * How to read the plans? Where to start modifying bash scripts?

Modifying bash scripts?

> * Load balancer backend set health is Unknown

Still Unknown? Takes few minutes to LB start to report the health.

**Comment by tuxerrante** [comment]
> @tuxerrante :
> 
> > Maybe the FAQ could be extended with these questions:
> > 
> > * How could I add the two VM in a instance pool from TF?
> 
> Can you elaborate more? You are looking for instructions to create an Instance Configuration, then a Instance Pool, and use the VMs from that pool?
Yes, we would like to switch on and off all the machines of the same cluster together, in addition to have the same hardware and software configuration.
 
> > * How to read the plans? Where to start modifying bash scripts?
It is not very clear how and in which order the scripts are called.
What we feel is missing more from the guide is an explanation of the terraform plans, such that anyone could start with your demo, replace their scripts (update OS, install docker..) and go on.
I've found a general introduction on [Oracle university - developing cloud native services](https://learn.oracle.com/ols/course/developing-cloud-native-applications-on-oci/35644/75242/102043), but maybe you have some more specific resource to understand what you have done :)

> > * Load balancer backend set health is Unknown
> 
> Still Unknown? Takes few minutes to LB start to report the health.
It took a little long, but now is OK, good.

Thanks again
great job

**Comment by junior** [comment]
@tuxerrante :

Quick question: Is this instance created after 12/15/2020?

> 
> Yes, we would like to switch on and off all the machines of the same cluster together, in addition to have the same hardware and software configuration.
> 

I'll include that on the roadmap

> 
> It took a little long, but now is OK, good.
> 

Awesome

**Comment by tuxerrante** [comment]
> @tuxerrante :
> 
> Quick question: Is this instance created after 12/15/2020?

Apr 1 2020
