### ISSUE TITLE
error - scripts not found

### ISSUE THREAD

**Issue by BernhardFW** [oracle-quickstart/oci-cloudnative#26]
Error: oci_objectstorage_object.apache_conf: 1 error occurred:
	* oci_objectstorage_object.apache_conf: file: open ./scripts/httpd.conf: no such file or directory in:
${file("./scripts/httpd.conf")}
Error: oci_objectstorage_object.entrypoint: 1 error occurred:
	* oci_objectstorage_object.entrypoint: file: open ./scripts/entrypoint.sh: no such file or directory in:
${file("./scripts/entrypoint.sh")}
Error: oci_objectstorage_object.catalogue_sql_script: 1 error occurred:
	* oci_objectstorage_object.catalogue_sql_script: file: open ./scripts/atp_mushop_catalogue.sql: no such file or directory in:
${file("./scripts/atp_mushop_catalogue.sql")}
Error: oci_objectstorage_object.mushop_basic: 1 error occurred:
	* oci_objectstorage_object.mushop_basic: file: open ./scripts/mushop-basic.tar.gz: no such file or directory in:
${file("./scripts/mushop-basic.tar.gz")}

[ocid1.ormjob.oc1.eu-frankfurt-1.aaaaaaaao6telhhn7v63r62sttij6m4vdaku7h6fiwxcttz2slxvai4qg4ha.log](https://github.com/oracle/oci-quickstart-cloudnative/files/3646397/ocid1.ormjob.oc1.eu-frankfurt-1.aaaaaaaao6telhhn7v63r62sttij6m4vdaku7h6fiwxcttz2slxvai4qg4ha.log)

**Comment by mvandervliet** [comment]
Hi @BernhardFW... Are you able to provide details on the stack file you uploaded, which resulted in these errors?. Presently I would suggest a retry in your tenancy using: [mushop-basic-stack-v1.0.2.zip](https://github.com/oracle/oci-quickstart-cloudnative/releases/download/v1.0.2/mushop-basic-stack-v1.0.2.zip)

**Comment by junior** [comment]
@BernhardFW the button <img width="147" alt="github_clone_download_button" src="https://user-images.githubusercontent.com/551007/65643018-3f446680-dfb6-11e9-8ec2-878403139c9f.png"> is a standard GitHub button to clone or download the entire repository. This does not download the release stack. We cannot change that button.

If you are cloning the repo, you can generate your own stack following these build [instructions](https://github.com/oracle/oci-quickstart-cloudnative/blob/master/deploy/basic/README.md).

On the main [README.md](https://github.com/oracle/oci-quickstart-cloudnative/blob/master/README.md), under the "Getting Started", the step 1, has the direct link for the pre-built stack release.

<img width="991" alt="main_README_stack_link" src="https://user-images.githubusercontent.com/551007/65643319-12448380-dfb7-11e9-80c3-1fc1926157bb.png">

**Comment by dude2222** [comment]
Hi, 
I had the same error Bernhard had - then I downloaded the file using the method Matthew mentioned.

Here is the latest error:

Error: Error applying plan:
1 error occurred:
	* oci_identity_policy.mushop_allow_object_storage_lifecycle: 1 error occurred:
	* oci_identity_policy.mushop_allow_object_storage_lifecycle: Service error:PolicyAlreadyExists. Policy 'mushop_allow_object_storage_lifecycle' already exists. http status code: 409. Opc request id: b869af6eb1c5d38fb66f524e52b6cc5c/A5BF1ED8DB1A1E8D7E26E13D3FD83D0F/D185F2A04ABD8AA3DBC5DE17D20FA05E

Any idea's on how to get past this?

Thanks.

**Comment by peterj** [comment]
@dude2222 are you saying that we shouldn't have closed this issue: https://github.com/oracle/oci-quickstart-cloudnative/issues/23 ? Because the error looks the same.

**Comment by dude2222** [comment]
Hi Peter,

I don't think so - after I applied the new tarball - this is the error I get - hence, the new tarball gives the same error as the one I applied two days ago.

I do think this is progress - albeit a little off-kilter - but still progress.

:-)

**Comment by peterj** [comment]
ok, can you re-open the #23  so we can track it there?

**Comment by dude2222** [comment]
Will do.

**Comment by peterj** [comment]
Closing this as stale. Please open a new issue if this persists.
