### ISSUE TITLE
Stack job doesn't finish successfully

### ISSUE THREAD

**Issue by adiplac** [oracle-quickstart/oci-cloudnative#271]
Running the complete deploy Terraform script, it finalizes with state: Failed with the following error:
```
2021/05/25 10:01:43[TERRAFORM_CONSOLE] [INFO] Error: marshaling request to a header requires not nil pointer for field: CompartmentId
2021/05/25 10:01:43[TERRAFORM_CONSOLE] [INFO]
2021/05/25 10:01:43[TERRAFORM_CONSOLE] [INFO]   on oke.tf line 5, in resource "oci_containerengine_cluster" "oke_cluster":
2021/05/25 10:01:43[TERRAFORM_CONSOLE] [INFO]    5: resource "oci_containerengine_cluster" "oke_cluster" {
```
Any suggestion to solve this problem?

**Comment by junior** [comment]
@adiplac can you list more details?

Have you copied the `terraform.tfvars.example` to `terraform.tfvars` and populated the data?

The minimum information is needed, like which tenancy that you are deploying, which compartment (can be the tenancy id in case you are deploying to the root compartment, I suggest you change `` to true if this be the case), and your user info.

```
# OCI authentication
tenancy_ocid     = "ocid1.tenancy....."
fingerprint      = "" # e.g.: "5f:53:..." or leave blank if using CloudShell
user_ocid        = "" # e.g.: "ocid1.user..." or leave blank if using CloudShell
private_key_path = "" # e.g.: "/users/user/.oci/oci_api_key.pem" or leave blank if using CloudShell

# Deployment compartment
compartment_ocid = "ocid1.compartment...."
...
create_new_compartment_for_oke = false
...
```

**Comment by adiplac** [comment]
Hi @junior ,
thanks for your response.
I ran the stack directly from the "Deploy to Oracle Cloud" button in the home.

I will try to edit the terraform.tfvars, but in the meanwhile I tried to create a OKE clouster standalone, and it fails as well (in my Tenancy, Frankfurt).

So I will check also if I have any problem in my Tenancy.

**Comment by junior** [comment]
@adiplac Did you solved the issue? Do you have rights to create a new cluster?

**Comment by adiplac** [comment]
Hi @junior thanks for asking.
I solved the issue today, Running Terraform script in another Region than Frankfurt it finishes successfully, 
I have to test if all services are created correctly, but it looks like no issues.

Probably some issues on Frankfurt Region on OKE service blocked the script.

**Comment by junior** [comment]
More likely that you do not have enough capacity limit on Frankfurt for OKE Clusters. You may require to increase the limit: https://cloud.oracle.com/support/service-request/create?region=eu-frankfurt-1 

Anyways, good to. know that you solved the issue.
