### ISSUE TITLE
Grafana - Local Port Forwarding into internal service

### ISSUE THREAD

**Issue by simon-neto** [oracle-quickstart/oci-cloudnative#291]
The installation of the helm chart returned the following output:

enable port forward
 kubectl port-forward -n mushop-utilities svc/mushop-utils-grafana 3000:80

access grafana via the url:
http://localhost:3000/grafana

but I receive the error message "too many redirects" on the browsers I tested (Firefox, Chrome, Safari).

When using the external load balancer URL from the service mushop-utils-ingress-nginx-controller it works.

I think is just a matter of updating the documentation and the helm chart output.

Can you explain if anything has changed on the connection trough the service?

Previously you would have:
kubectl port forward > workstation > mushop-utils-grafana (ExternalName service) > pod

Now we have 
workstation > mushop-utils-ingress-nginx-controller (Load Balancer) > mushop-utils-grafana ( ExternalName service) > pod

**Comment by junior** [comment]
That's an old forgotten update to the notes helm. I'll be updating on the next release.

For now, use the command:
```bash
kubectl port-forward -n mushop-utilities svc/mushop-utils-ingress-nginx-controller 4000:80
```

This will give you access to the Grafana using `http:/localhost:4000/grafana` and the Storefront using `http://localhost:4000/`

**Comment by junior** [comment]
The above comment will only work after you deploy the MuShop chart, which creates the ingress.

I've also updated the Grafana configurations to allow the port-forward direct to Grafana from the service, in case need to access even if just deployed the mushop-utilities....
....so the command `kubectl port-forward -n mushop-utilities svc/mushop-utils-grafana 3000:80` will also work

**Comment by simon-neto** [comment]
Thanks!!! I managed to get it working with the public IP. I just placed the issue to keep record of the documentation in the future.
Thanks Adao

**Comment by junior** [comment]
PR #293 fix the issue
