### ISSUE TITLE
BASIC - terraform script failing

### ISSUE THREAD

**Issue by Raj-Krishnamoorthy** [oracle-quickstart/oci-cloudnative#292]
I got the following error when I ran the basic option. I think tf scripts needs to be updated. Please advise. Here is attached output log.

-----output-------

2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] Initializing provider plugins...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Finding hashicorp/tls versions matching "3.1.0"...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Finding hashicorp/oci versions matching ">= 4.36.0"...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Finding hashicorp/local versions matching "2.1.0"...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Finding hashicorp/random versions matching "3.1.0"...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Finding latest version of hashicorp/template...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/random v3.1.0...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/random v3.1.0 (unauthenticated)
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/template v2.1.2...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/template v2.1.2 (unauthenticated)
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/tls v3.1.0...
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/tls v3.1.0 (unauthenticated)
2021/09/03 17:08:20[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/oci v4.42.0...
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/oci v4.42.0 (unauthenticated)
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/local v2.1.0...
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/local v2.1.0 (unauthenticated)
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] Terraform has created a lock file .terraform.lock.hcl to record the provider
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] selections it made above. Include this file in your version control repository
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] so that Terraform can guarantee to make the same selections by default when
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] you run "terraform init" in the future.
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] Terraform has been successfully initialized!
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] You may now begin working with Terraform. Try running "terraform plan" to see
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] any changes that are required for your infrastructure. All Terraform commands
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] should now work.
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] If you ever set or change modules or backend configuration for Terraform,
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] rerun this command to reinitialize your working directory. If you forget, other
2021/09/03 17:08:22[TERRAFORM_CONSOLE] [INFO] commands will detect it and remind you to do so if necessary.
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] Warning: "object": [DEPRECATED] The 'object' field has been deprecated. Please use 'object_name' instead.
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO]   with oci_objectstorage_preauthrequest.mushop_wallet_preauth,
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO]   on storage.tf line 20, in resource "oci_objectstorage_preauthrequest" "mushop_wallet_preauth":
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO]   20: resource "oci_objectstorage_preauthrequest" "mushop_wallet_preauth" {
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] (and 3 more similar warnings elsewhere)
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] Error: Null value found in list
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO]   with data.oci_identity_regions.home_region,
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO]   on datasources.tf line 106, in data "oci_identity_regions" "home_region":
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO]  106: data "oci_identity_regions" "home_region" {
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] 
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO] Null values are not allowed for this attribute value.
2021/09/03 17:08:34[TERRAFORM_CONSOLE] [INFO]

**Comment by junior** [comment]
@Raj-Krishnamoorthy, when deploying using local terraform or cloud shell, you need to use the terraform.tfvars to update the variables, and for the MuShop basic, you have an extra step to get the images and scripts needed.

Instructions here: https://github.com/oracle-quickstart/oci-cloudnative/tree/master/deploy/basic#deploying-using-local-or-cloudshell-terraform-instead-of-orm-stack

**Comment by junior** [comment]
@Raj-Krishnamoorthy did you were able to run after fill the tfvars?
