### ISSUE TITLE
entity: nodepool, action: CREATED. Message: 3 node(s) launch failure

### ISSUE THREAD

**Issue by norberto-enomoto** [oracle-quickstart/oci-cloudnative#297]
I'm trying to deploy the demo and I'm getting the following error: 
entity: nodepool, action: CREATED. Message: 3 node(s) launch failure

I'm using a trial account and the region is Brazil East (Sao Paulo)

Complete stack trace:

2021/11/08 22:23:50 [[INFO]] oci_containerengine_cluster.oke_cluster[0]: Creation complete after 6m38s [id=ocid1.cluster.oc1.sa-saopaulo-1.aaaaaaaanivptsssjn7vhhsp5efb5kmjfsbphtgtrx3legwkkcghxzuvr4ua]
2021/11/08 22:23:50 [[INFO]] oci_containerengine_node_pool.oke_node_pool[0]: Creating...
2021/11/08 22:24:00 [[INFO]] oci_containerengine_node_pool.oke_node_pool[0]: Still creating... [10s elapsed]
2021/11/08 22:24:10 [[INFO]] oci_containerengine_node_pool.oke_node_pool[0]: Still creating... [20s elapsed]
2021/11/08 22:24:14 [[INFO]] 
2021/11/08 22:24:14 [[INFO]] Error: work request did not succeed, workId: ocid1.clustersworkrequest.oc1.sa-saopaulo-1.aaaaaaaakwatuw7eh2yyix3alhw4uslct6eetxp6ynpidmjdzwdr62hmguoq, entity: nodepool, action: CREATED. Message: 3 node(s) launch failure
2021/11/08 22:24:14 [[INFO]] 
2021/11/08 22:24:14 [[INFO]]   with oci_containerengine_node_pool.oke_node_pool[0],
2021/11/08 22:24:14 [[INFO]]   on oke.tf line 34, in resource "oci_containerengine_node_pool" "oke_node_pool" 
2021/11/08 22:24:14 [[INFO]]   34: resource "oci_containerengine_node_pool" "oke_node_pool" {
2021/11/08 22:24:14 [[INFO]]  
2021/11/08 22:24:14 [[INFO]]

**Comment by junior** [comment]
@norberto-enomoto what is the reason that the work request did not succeed?

You can check on the work requests 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/551007/140831139-8921eb16-a00f-45f8-a786-b573a31ba733.png">

Maybe you do not have the capacity for the shapes used to create the node pool.
