### ISSUE TITLE
unable to destroy  the job

### ISSUE THREAD

**Issue by najioullah** [oracle-quickstart/oci-cloudnative#298]
whan i try to destroy I get this:
Error: Invalid function argument
  on datasources.tf line 87, in locals:
  87:   file("ERROR: No limits available for the chosen compute shape and number of nodes or OCPUs")) : 0
Invalid value for "path" parameter: no file exists at ERROR: No limits
available for the chosen compute shape and number of nodes or OCPUs; this
function works only with files that are distributed as part of the
configuration source code, so if this file will be created by a resource in
this configuration you must instead obtain this result from an attribute of
that resource.

**Comment by junior** [comment]
@najioullah Do you know which version of the basic stack are you using it?

**Comment by najioullah** [comment]
@adao i am usign this mushop-basic-stack-latest.zip
<https://github.com/oracle-quickstart/oci-cloudnative/releases/latest/download/mushop-basic-stack-latest.zip>
downloaded
from https://github.com/oracle-quickstart/oci-cloudnative
Thanks

Le jeu. 9 déc. 2021 à 00:27, Adao Junior ***@***.***> a
écrit :

**Comment by najioullah** [comment]
Please, could you tell me how may i know the version i am using?
Thanks

**Comment by junior** [comment]
Inside the stack you have a VERSION file. I'm planing to expose this on the OUTPUT as well, I may include on the next release.

**Comment by junior** [comment]
@najioullah did you fixed or was able to get the version?
