### ISSUE TITLE
ORM Apply fails with Error: Waiting for rollout to finish: 3 replicas wanted; 0 replicas Ready

### ISSUE THREAD

**Issue by andytael** [oracle-quickstart/oci-cloudnative#299]
I tried deploying MuShop using "Deploy to Oracle Cloud" button (https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://github.com/oracle-quickstart/oci-cloudnative/releases/latest/download/mushop-stack-latest.zip) and the Apply job failed with the following error:

`2021/12/09 16:31:27[TERRAFORM_CONSOLE] [INFO] kubernetes_deployment.cluster_autoscaler_deployment[0]: Still creating... [9m40s elapsed]
2021/12/09 16:31:37[TERRAFORM_CONSOLE] [INFO] kubernetes_deployment.cluster_autoscaler_deployment[0]: Still creating... [9m50s elapsed]
2021/12/09 16:31:47[TERRAFORM_CONSOLE] [INFO] 
2021/12/09 16:31:47[TERRAFORM_CONSOLE] [INFO] Error: Waiting for rollout to finish: 3 replicas wanted; 0 replicas Ready
2021/12/09 16:31:47[TERRAFORM_CONSOLE] [INFO] 
2021/12/09 16:31:47[TERRAFORM_CONSOLE] [INFO]   with kubernetes_deployment.cluster_autoscaler_deployment[0],
2021/12/09 16:31:47[TERRAFORM_CONSOLE] [INFO]   on oke-autoscaler.tf line 190, in resource "kubernetes_deployment" "cluster_autoscaler_deployment":
2021/12/09 16:31:47[TERRAFORM_CONSOLE] [INFO]  190: resource "kubernetes_deployment" "cluster_autoscaler_deployment" {
2021/12/09 16:31:47[TERRAFORM_CONSOLE] [INFO] 
2021/12/09 16:31:47[TERRAFORM_CONSOLE] [INFO] `

**Comment by junior** [comment]
That's a known issue generated because of the change on the autoscaler images tags. On the current stack, I recommend not to use Cluster Autoscaler if using version Kubernetes 1.20+ or latest.

A fix will be created by this EOW.

**Comment by junior** [comment]
Fixes delayed for next week

**Comment by junior** [comment]
The work around is to disable the cluster autoscaler if want to use 1.20 or 1.21 (latest) or extract the zip, change the file ole-autoscaler.tf line 7 and change the `cluster_autoscaler_image_version` to 1-1 (if 1.21) or 0-4 (if 1.20) and change the line 8 (col 132) to use "." instead of "-" for the version separator (will looks like this: `.../oci-cluster-autoscaler:${local.k8s_major_minor_version}.${local.cluster_autoscaler_image_version}`)
