### ISSUE TITLE
Mushop free tier Terraform error

### ISSUE THREAD

**Issue by mkratky** [oracle-quickstart/oci-cloudnative#31]
Hi,
I'm getting the following errors when applying the Mushop basic resource manager stack:

2 errors occurred:
	* oci_core_nat_gateway.mushopNat: 1 error occurred:
	* oci_core_nat_gateway.mushopNat: Service error:LimitExceeded. NAT gateway limit per VCN reached. http status code: 400. Opc request id: ae77a4d41495cbd3de5a52e8eb8337bc/A3BA31EBE6075E6E67C818DF7E40B170/A4D3C0DCF86690B80178F16FA443F0C4
	* oci_core_service_gateway.mushopSGW: 1 error occurred:
	* oci_core_service_gateway.mushopSGW: Service error:InvalidParameter. The maximum limit of 0 for Service gateway per VCN has been exceeded in VCN ocid1.vcn.oc1.eu-frankfurt-1.aaaaaaaawoynhtclagxyz2zxgnru636v7gy3tpj4yyzeoc6ljxoyial5orxq.. http status code: 400. Opc request id: b3acb66ed4a7e06a30fd72a004ec768b/A439D2CEDCCC9A499DFF0085E605C3C6/5ADAAEEF00ED5CF651D25EB1EEE81BE1

**Comment by mvandervliet** [comment]
This can happen if the trial period has expired and the account has not been upgraded. We are working on a solution to this problem

**Comment by junior** [comment]
@mkratky can you please try to use the new stack? [mushop-basic-stack-v1.0.3.zip](https://github.com/oracle-quickstart/oci-cloudnative/releases/download/v1.0.3/mushop-basic-stack-v1.0.3.zip)

This version does not require NAT gateway, and you will be able to use the pure Always Free resources, even if the trial have been expired.

**Comment by jeevanjoseph** [comment]
Closing - this is fixed in release 1.0.3 as @junior mentioned. See #36 for more details.
