### ISSUE TITLE
Unable to create withe stack - encountering error in oracle autoscaler

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [oracle-quickstart/oci-cloudnative#314]
my first deployment failed due to api-gateway limit issue. after the increase of the api-gateway, I tried to reapply the same but it started failing at the validation check on the "cluster_autoscaler" section.

`
Error: Get "http://localhost/apis/rbac.authorization.k8s.io/v1/clusterroles/secret-creator": dial tcp [::1]:80: connect: connection refused
  with kubernetes_cluster_role.secret_creator[0],
  on mushop-oci-services.tf line 76, in resource "kubernetes_cluster_role" "secret_creator" 
  76: resource "kubernetes_cluster_role" "secret_creator" {
Error: Get "http://localhost/api/v1/namespaces/mushop-utilities": dial tcp [::1]:80: connect: connection refused
  with kubernetes_namespace.cluster_utilities_namespace,
  on mushop-utilities.tf line 6, in resource "kubernetes_namespace" "cluster_utilities_namespace" 
   6: resource "kubernetes_namespace" "cluster_utilities_namespace" {
Error: Get "http://localhost/api/v1/namespaces/mushop": dial tcp [::1]:80: connect: connection refused
  with kubernetes_namespace.mushop_namespace,
  on mushop.tf line 6, in resource "kubernetes_namespace" "mushop_namespace" 
   6: resource "kubernetes_namespace" "mushop_namespace" {
Error: Get "http://localhost/api/v1/namespaces/kube-system/serviceaccounts/cluster-autoscaler": dial tcp [::1]:80: connect: connection refused
  with kubernetes_service_account.cluster_autoscaler_sa[0],
  on oke-autoscaler.tf line 20, in resource "kubernetes_service_account" "cluster_autoscaler_sa" 
  20: resource "kubernetes_service_account" "cluster_autoscaler_sa" {
Error: Get "http://localhost/apis/rbac.authorization.k8s.io/v1/clusterroles/cluster-autoscaler": dial tcp [::1]:80: connect: connection refused
  with kubernetes_cluster_role.cluster_autoscaler_cr[0],
  on oke-autoscaler.tf line 35, in resource "kubernetes_cluster_role" "cluster_autoscaler_cr" 
  35: resource "kubernetes_cluster_role" "cluster_autoscaler_cr" {
Error: Get "http://localhost/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/cluster-autoscaler": dial tcp [::1]:80: connect: connection refused
  with kubernetes_role.cluster_autoscaler_role[0],
  on oke-autoscaler.tf line 116, in resource "kubernetes_role" "cluster_autoscaler_role" 
 116: resource "kubernetes_role" "cluster_autoscaler_role" {
Error: Get "http://localhost/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/cluster-autoscaler": dial tcp [::1]:80: connect: connection refused
  with kubernetes_cluster_role_binding.cluster_autoscaler_crb[0],
  on oke-autoscaler.tf line 142, in resource "kubernetes_cluster_role_binding" "cluster_autoscaler_crb" 
 142: resource "kubernetes_cluster_role_binding" "cluster_autoscaler_crb" {
Error: Get "http://localhost/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/cluster-autoscaler": dial tcp [::1]:80: connect: connection refused
  with kubernetes_role_binding.cluster_autoscaler_rb[0],
  on oke-autoscaler.tf line 165, in resource "kubernetes_role_binding" "cluster_autoscaler_rb" 
 165: resource "kubernetes_role_binding" "cluster_autoscaler_rb" {
Error: Get "http://localhost/apis/apps/v1/namespaces/kube-system/deployments/cluster-autoscaler": dial tcp [::1]:80: connect: connection refused
  with kubernetes_deployment.cluster_autoscaler_deployment[0],
  on oke-autoscaler.tf line 190, in resource "kubernetes_deployment" "cluster_autoscaler_deployment" 
 190: resource "kubernetes_deployment" "cluster_autoscaler_deployment" {`

**Comment by junior** [comment]
That's an issue with the Terraform Kubernetes Provider working with the Terraform OCI provider on the OCI Resource Manager.

You need to set the refresh=false.

If using local terraform, you can destroy by using `terraform destroy -refresh=false`.

If using OCI Resource Manager, when destroying, open the "Show Advanced Options" and uncheck the refresh resources, like shown on the image bellow:
![image](https://user-images.githubusercontent.com/551007/155573006-989b6c5b-3046-42e0-bd13-4a211360f53e.png)

**Comment by junior** [comment]
@kollachaitanyakrishna please confirm that the issue have been solved and close if is the case
