### ISSUE TITLE
ORM: Kubernetes provider could fail when `cluster_endpoint_visibility` set to "Private"

### ISSUE THREAD

**Issue by nom3ad** [oracle-quickstart/oci-cloudnative#316]
https://github.com/oracle-quickstart/oci-cloudnative/pull/243 added new feature to set Kubernetes API Endpoint to be Public or Private.  But when using ORM,  private OKE endpoint wouldn't be reachable. Isn't it?

Though, I couldn't test this to verify. But I believe that it would definitely fail to deploy if someone chose “Kubernetes API Endpoint visibility type”  option to be “Private”.

**Comment by junior** [comment]
@nom3ad full support to Private K8s endpoint is on this stack roadmap. Today you can archive by using an oci bastion service, which will be included on the scripts someday for the one-click deployment.

Do you have specific requirements now?

**Comment by nom3ad** [comment]
I was referring this project to develop a one-click deployment solution (Using  OCI Resource Manager) for another project. After provisioning OKE with private endpoint, I want to deploy application stack using Kubernetes/Helm providers. 
 
Currently, my workflow is like -
	- Provision OCI infrastructure, which includes Private OKE and Bastion Service (Can do that from local machine / ORM)
	- Generate OKE K8s Config file.  Update it with a localhost:8080 API endpoint and add it to the local machine (Manual step)
	- Start SSH port forwarding session to K8s API endpoint on localhost:8080 through Bastion.  (Manual Step)
	- Use kubectl from local machine to apply some manifests (Manual Step)
	- Kick off Helm deployment directly from local machine  (Manual Step)
	- Stop port forwarding session (Manual Step)
	
I would like to automate  everything using ORM.  But couldn't  figure out how to use Kubernetes/Helm providers when OKE endpoint is private. 

Do you happen to know a way to use OCI Bastion service from ORM? Then that would solve my use case, I think.

Thanks.

**Comment by junior** [comment]
You do not need to use "from ORM". The resource bastion will be created before the use of the Kubernetes provider. The kubernetes endpoint will use the bastion endpoint.

**Comment by nom3ad** [comment]
@junior 
just in case you missed my last reply,  I've tried to my use case further.

**Comment by nom3ad** [comment]
@junior
just in case you missed my last reply, I've tried to elaborate my use case further.

Edit: typo

**Comment by junior** [comment]
ORM just launch the feature to connect from ORM to a private endpoint, that way the complete stack will be able to run the Kubernetes and Helm commands against the k8s private endpoint. I'm OOO this next week, and will take a look on this as soon I get back.

**Comment by junior** [comment]
I've also made some changes to separate the OKe cluster creation from the MuShop deployment, which will help more to implement that on a single Stack.
