### ISSUE TITLE
Error Message: work request did not succeed, workId: ocid1.clustersworkrequest.oc1.iad.aaaaaaaaartjvegvp4rq2exos6xhk4zln42retiou5dyhjlvwwxaussf7cna, entity: nodepool, action: CREATED. Message: 1 node(s) launch failure

### ISSUE THREAD

**Issue by jcbolivar-07** [oracle-quickstart/oci-cloudnative#324]
Hi;

I have been trying to deploy MuShop Complete: deploy/complete, but I am getting the following error while the stack deployment:

oci_containerengine_node_pool.oke_node_pool[0]: Still creating... [3m40s elapsed]

Error: Work Request error
Provider version: 4.74.0, released on 2022-05-04.
Service: Containerengine Node Pool
Error Message: work request did not succeed, workId: ocid1.clustersworkrequest.oc1.iad.aaaaaaaaartjvegvp4rq2exos6xhk4zln42retiou5dyhjlvwwxaussf7cna, entity: nodepool, action: CREATED. Message: 1 node(s) launch failure
Resource OCID: ocid1.nodepool.oc1.iad.aaaaaaaalykrliaazrge5ohup2m27ohuusbbesh5wx5qyge6tnyumufuznza
Suggestion: Please retry or contact support for help with service: Containerengine Node Pool
  
  with oci_containerengine_node_pool.oke_node_pool[0],
  on oke.tf line 41, in resource "oci_containerengine_node_pool" "oke_node_pool" 
  41: resource "oci_containerengine_node_pool" "oke_node_pool" {

Could you help me to identify the reason of this issue, please?

**Comment by junior** [comment]
Go to the OCI Console, on the cluster > Node Pool, and see the logs on the work requests. May have information of what happened.
