### ISSUE TITLE
When using Resource Manager Task it fails when trying to authenticate

### ISSUE THREAD

**Issue by luissimoesneom** [oracle-quickstart/oci-cloudnative#330]
Hi,

Authentication is failing on OCI provider. Do I need to specify a TFVARS file with the fingerprint and private_key?
Where do we store the private key file?

Thank you

**Comment by jeevanjoseph** [comment]
Can you provide details on how you got this error ? Like how you were trying to set it up. 
If you click on the deploy button (see below) 
<img width="289" alt="image" src="https://user-images.githubusercontent.com/5790082/184249157-e5e288e1-1016-4b7d-b5e6-be230c507964.png">

You dont need to provide any TFVARS. If you are running terraform locally, you need to edit [terraform.tfvars.example](https://github.com/oracle-quickstart/oci-cloudnative/blob/master/deploy/complete/terraform/terraform.tfvars.example) we provide and rename it to `terraform.tfvars`

**Comment by junior** [comment]
You probably have experienced the issue with the Terraform OCI Provider as listed here: https://github.com/oracle/terraform-provider-oci/issues/1650

Try again now as this have been fixed.

**Comment by luissimoesneom** [comment]
My goal was to understand how the user_ocid, fingerprint and private_key_file variables are passed to the OCI Resource Manager Stack.... How is it supposed to authenticate? Do we need to specify those? If so, how?
