### ISSUE TITLE
me indica el error "Dockerfile parse error line 55: Unknown flag: chmod"

### ISSUE THREAD

**Issue by Fabrijlle** [oracle-quickstart/oci-cloudnative#331]
al momento de hacer una nueva versión con el parámetro
docker build --build-arg version=2.0.2-beta -t mushop/storefront ~/mushop/src/storefront
me arroja el error de dockerfile como lo puedo solucionar

**Comment by nnarvaez** [comment]
I have the same error.

**Comment by TheKoguryo** [comment]
Use this command.
**DOCKER_BUILDKIT=1** docker build --build-arg version=2.0.2-beta -t mushop/storefront ~/mushop/src/storefront
