### ISSUE TITLE
I am getting an error when I try to MuShop complete on our Tenancy.https://github.com/oracle-quickstart/oci-cloudnative 

### ISSUE THREAD

**Issue by DineshMaricherla** [oracle-quickstart/oci-cloudnative#332]
The error is as as shown below:

2022/10/18 17:10:38 [[INFO]] data.kubernetes_secret.mushop_utils_grafana[0]: Read complete after 0s [id=mushop-utilities/mushop-utils-grafana]
2022/10/18 17:10:38 [[INFO]] 
2022/10/18 17:10:38 [[INFO]] Error: Waiting for default secret of "mushop/wallet-extractor-sa" to appear
2022/10/18 17:10:38 [[INFO]] 
2022/10/18 17:10:38 [[INFO]]   with kubernetes_service_account.wallet_extractor_sa[0],
2022/10/18 17:10:38 [[INFO]]   on mushop-oci-services.tf line 105, in resource "kubernetes_service_account" "wallet_extractor_sa" 
2022/10/18 17:10:38 [[INFO]]  105: resource "kubernetes_service_account" "wallet_extractor_sa" {
[ocid1.ormjob.oc1.iad.amaaaaaakrqjwoialfwtyth6zonhafewjwd4cwcz46knuvqwop75xb4vc2iq.log](https://github.com/oracle-quickstart/oci-cloudnative/files/9814146/ocid1.ormjob.oc1.iad.amaaaaaakrqjwoialfwtyth6zonhafewjwd4cwcz46knuvqwop75xb4vc2iq.log)

**Comment by DineshMaricherla** [comment]
Can I please get some help on this?

**Comment by streamnsight** [comment]
same here. it always fails there. I tried several times.

**Comment by streamnsight** [comment]
seems to be related to this issue:
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1724

where the workaround is to use a manifest resource to create the Service Account

**Comment by streamnsight** [comment]
I realize this is not available on apply unless the cluster exists, so that's not really an option.

**Comment by streamnsight** [comment]
I got the SA issue to work by upgrading to kubernetes provider v2.13

note this is an issue with Kubernetes v1.24+ and if you are using v1.24+, there are other issues, including the cluster-autoscaler config that need to change according to the docs (https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm) where cloud-provider needs to change from `oci` to `oci-oke`.

**Comment by junior** [comment]
The cluster autoscaler is a different subject and the OKE creation is being decoupled from main MuShop to allow MuShop use just one stack for multi-cloud. If you want to see the scripts to create just the base OKE with Cluster Autoscaler and Cluster Tools, refer to https://github.com/oracle-quickstart/terraform-oci-oke-quickstart

**Comment by junior** [comment]
Issue fixed, updated and tested up to OKE 1.29.
