### ISSUE TITLE
The job failed due to an error in the Terraform configuration

### ISSUE THREAD

**Issue by jasoncmcg** [oracle-quickstart/oci-cloudnative#34]
Uploaded the mushop-basic-stack-v1.0.2.zip and applied it.
Status: Failed
Error: The job failed due to an error in the Terraform configuration.

Terraform state attached.

[ocid1.ormjob.oc1.iad.aaaaaaaa7jvgt6gch6zjcyxjdre44bdoxtnhymlpq6m23etjncqxu5l4pxuq.txt](https://github.com/oci-quickstart/oci-cloudnative/files/3764118/ocid1.ormjob.oc1.iad.aaaaaaaa7jvgt6gch6zjcyxjdre44bdoxtnhymlpq6m23etjncqxu5l4pxuq.txt)

**Comment by junior** [comment]
Here @jasoncmcg. The terraform state that you attached doesn't show any errors. Actually shows that was successfully deployed to http://150.136.197.14.

Do you have more details on which error you have received?

**Comment by junior** [comment]
@jasoncmcg any updates on your test? Any remaining errors?

**Comment by jeevanjoseph** [comment]
@jasoncmcg bump
