### ISSUE TITLE
Micro shapes not available in FRA, reconfigured main.tf but fails to find scripts

### ISSUE THREAD

**Issue by mikarinneoracle** [oracle-quickstart/oci-cloudnative#35]
https://github.com/oci-quickstart/oci-cloudnative/blob/master/deploy/basic/terraform/main.tf#L63
=> instance_shape = "VM.Standard2.1"

I zipped the project source and deployed but giving errors:
Error: oci_objectstorage_object.mushop_basic: 1 error occurred:
    * oci_objectstorage_object.mushop_basic: file: open ./scripts/mushop-basic.tar.gz: no such file or directory in:
${file("./scripts/mushop-basic.tar.gz")}
Error: oci_objectstorage_object.apache_conf: 1 error occurred:
    * oci_objectstorage_object.apache_conf: file: open ./scripts/httpd.conf: no such file or directory in:
${file("./scripts/httpd.conf")}
Error: oci_objectstorage_object.entrypoint: 1 error occurred:
    * oci_objectstorage_object.entrypoint: file: open ./scripts/entrypoint.sh: no such file or directory in:
${file("./scripts/entrypoint.sh")}
Error: oci_objectstorage_object.catalogue_sql_script: 1 error occurred:
    * oci_objectstorage_object.catalogue_sql_script: file: open ./scripts/atp_mushop_catalogue.sql: no such file or directory in:
${file("./scripts/atp_mushop_catalogue.sql")}

**Comment by mikarinneoracle** [comment]
I modified the mushop-basic-stack-v1.0.2.zip file with the change above and looks better, but still fails to another error:
Error: Error applying plan:
1 error occurred:
	* oci_core_instance.app-instance: 1 error occurred:
	* oci_core_instance.app-instance: Service error:InvalidParameter. Invalid availabilityDomain. http status code: 400. Opc request id: c48d2925fe501ffc57135a5e0e8eea0d/0C0E93098BE9C0DB1433A61F987D5E89/5D020CD367B3D0F45F8B4245D3ED4D6A

**Comment by junior** [comment]
Microshapes are available on FRA. Remember that micro-shapes are only available on your home region.

When making changes on the stack, you can build (create the zip) by using these instructions: https://github.com/oracle-quickstart/oci-cloudnative/tree/master/deploy/basic#build 

Just zipping the repo will not have the necessary files to run the stack.

**Comment by mikarinneoracle** [comment]
ok, thanks!

Is there a way to "rollback" all the created resources uysinbg TerraForm with the Resource Manager and this demo ?

**Comment by junior** [comment]
To "rollback", you just need to go to your stack and  hit `destroy` in the menu.

We just released a [new stack (mushop-basic-stack-v1.0.3.zip)](https://github.com/oracle-quickstart/oci-cloudnative/releases/download/v1.0.3/mushop-basic-stack-v1.0.3.zip) with a change that auto select the AD where you have free shapes. You just need to make sure that you are on your home region.

**Comment by mikarinneoracle** [comment]
Ok, my experience is that if/since the install failed removing/destroying the stack did not remove the resources. But I have to take another look. When running this multiple times and failing and destroying the stack I could see all the resources pile up in my cloud account.
