### ISSUE TITLE
terraform scripts to build the full MuShop application 

### ISSUE THREAD

**Issue by jtsaismith** [oracle-quickstart/oci-cloudnative#37]
Where can I find the Terraform scripts to create the full MuShop application (with shopping cart, etc.)? Here's a diagram of the full application I found in on the "About" page of the basic application: 

![image](https://user-images.githubusercontent.com/7684447/68275743-5c426f80-0021-11ea-9b86-ecb6bd813de6.png)

Thanks,
Jenny

**Comment by junior** [comment]
Hello Jenny. If you want to deploy the full application with all services, you can refer to the /deploy/complete folder. There's instructions on how to deploy using helm charts here: https://github.com/oracle-quickstart/oci-cloudnative/tree/master/deploy/complete/helm-chart 

We are working to have Terraform/Resource manager stack to do the deploy seamlessly like the basic.

**Comment by jeevanjoseph** [comment]
@jtsaismith , this was implemented by @junior and is now available in the repo. Can we close this ?

**Comment by junior** [comment]
https://github.com/oracle-quickstart/oci-cloudnative/tree/master/deploy/complete/terraform
