### ISSUE TITLE
OCI WAF is not working with OKE-based MuShop

### ISSUE THREAD

**Issue by mahmoudrabie** [oracle-quickstart/oci-cloudnative#371]
Dear MuShop Team,

I have configured OCI WAF policy that protects VM-based (basic deployment) and OKE-bassd (complete deployment) MuShop.

It is working perfectly with VM-based MuShop. For example, it returns 401 for the unauthorized access.

However, OKE-based MuShop is not working with OCI-WAF and not returning the expected responses.

Are there special annotation need to be added to the ingress to make OCI WAF working with OKE. For instance, AWS WAF and AWS EKS need such annotation here
https://aws.amazon.com/blogs/containers/protecting-your-amazon-eks-web-apps-with-aws-waf/

I would appreciate your help at the earliest 

Kind regards
Mahmoud

**Comment by junior** [comment]
You do not need anything extra to use WAF. The demo website uses WAF: https://mushop.ateam.cloud

**Comment by junior** [comment]
MuShop's (OKE Based) WAF Policy is simple. The SSL certificate generated by the cert-manager on Kubernetes is imported to WAF; HTTPS is enforced; TLS 1.2 and 1.3.

If using the OCI DNS Management, the WAF CNAME endpoint created need to point to a subdomain on your FQDN. Example DNS Records:

| Domain                 | TTL | Type  | RDATA                                                |                                                                |
|------------------------|-----|-------|------------------------------------------------------|----------------------------------------------------------------|
| waf.mushop.example.com | 300 | CNAME | mushop-example-com.x.waas.oci.oraclecloud.net.       | * WAF CNAME Target available on the WAF Policy Details         |
| mushop.example.com     | 60  | ALIAS | waf.mushop.example.com.                              |                                                                |
| mushop.example.com     | 60  | A     | 11.22.33.44 occluded by ALIAS waf.mushop.example.com | * 11.22.33.44 is the LoadBalancer IP of the Ingress Controller |

**Comment by junior** [comment]
And of course, the WAF Origin URI need to be the Ingress Service IP. I use IP_HASH as Load balancing method and the only thing "custom" is the header X-OCI-WAF:true, used by some tutorials

**Comment by mahmoudrabie** [comment]
Thanks @junior for your detailed answer

Will that work with OCI WAF or it is for OCI WAF(Edge)(Legacy) only?

**Comment by mahmoudrabie** [comment]
@junior 
Any updates?

**Comment by junior** [comment]
Currently is working with WAF (edge), accessible using https://cloud.oracle.com/waf. Is this the one that you are calling legacy?

You can also use the WAF enabled LoadBalancer. 

Which OCI WAF/WaaS exactly you are talking about?

**Comment by mahmoudrabie** [comment]
Thanks @junior for your prompt response

**Which OCI WAF/WaaS exactly you are talking about?**
We are using the regular policy not the Edge one.
Please check this one 
https://drive.google.com/file/d/10k6SeDZjrXz2jof5_of6L3q_1xrQ5hV-/view?usp=sharing

**Comment by mahmoudrabie** [comment]
Finally I found the root cause.

The provisioned LB' two listeners are:
- TCP 443
- TCP 80

The OCI WAF worked perfectly when I changed the listeners to:
- HTTPS 443
- HTTP 80

My recommendation to Oracle team to change the Terraform code to provision the listeners with right aforementioned protocols

Special thanks to @junior
