### ISSUE TITLE
Creating 3 Tier Website

### ISSUE THREAD

**Issue by BAYOAKINS** [oracle-quickstart/oci-cloudnative#38]
Hello, please I got an assignment that leads me to your web page; https://github.com/oci-quickstart/oci-cloudnative

I am to create a 3 Tier Website. I have my OCI free account, and I already downloaded and uploaded the zip file as instructed on your website. 
Please, how or where do I go next? Or what do I need to do next? How do I create the 3 Tier Website?

I look forward to hearing from you soon.
Thank you.

Adebayo Akinsipe

**Comment by jtsaismith** [comment]
Adebayo - After you uploaded the .zip file in OCI > Resource Manager > Create Stack, did you then to to the uploaded stack and click Terraform Actions > Apply? Once you do this, it will take about 5 minutes for the Terraform scripts to automatically run. These scripts will create, configure, and start up the database, VMs, virtual network, load balancer. You can view the Terraform log as the scripts are running (go to OCI > Resource Manager > Stack > Job > Log. After all scripts complete successfully, scroll to the bottom of the Terraform log, and you'll see an Outputs section. Locate the lb_public_url value (e.g., http://150.111.111.111) - that's the URL for your new 3-tier website!

**Comment by BAYOAKINS** [comment]
Hello Jenny,Thank you very much for your step by step explanation. I did all that initially and I got the following final message at the bottom:
Outputs:autonomous_database_password = 9u*8]]RuHPw{k3f[comments = The application URL will be unavailable for a few minutes after provisioning, while the application is configureddev = Made with ❤ by Oracle A-Teamlb_public_url = http://150.136.198.169  


The URL opened up a MuShop page. Is that the 3 Tier website? Thank you for your time.
Adebayo Akinsipe

-----Original Message-----

**Comment by BAYOAKINS** [comment]
Hello Jenny,Thank you very much for your step by step explanation. I did all that initially and I got the following final message at the bottom:
Outputs:autonomous_database_password = 9u*8]]RuHPw{k3f[comments = The application URL will be unavailable for a few minutes after provisioning, while the application is configureddev = Made with ❤ by Oracle A-Teamlb_public_url = http://150.136.198.169 ; 


The URL opened up a MuShop page. Is that the 3 Tier website? Thank you for your time.
Adebayo Akinsipe

-----Original Message-----

**Comment by jtsaismith** [comment]
Adebayo - yes, MuShop is the 3-tier website.

Best,
Jenny

**Comment by jeevanjoseph** [comment]
Can this issue be closed ?

**Comment by BAYOAKINS** [comment]
Yes please, thank you.


-----Original Message-----
