### ISSUE TITLE
Problem with accessing the Load Balancer for the latest basic deployment ( 502 Bad Gateway )

### ISSUE THREAD

**Issue by ahmedmansour5** [oracle-quickstart/oci-cloudnative#382]
I have used the latest basic deployment on OCI using the images below:

[root@mushop-jnkv-1 ~]# cat /etc/oracle-release 
Oracle Linux Server release 7.9

[root@mushop-6urs-0 ~]# cat /etc/oracle-release
Oracle Linux Server release 8.7
</br>

Both deployments went through successfully but the Load Balancer returned **502 Bad Gateway** in both cases.
</br>
The load balancer backend health check is returning **Critical - Status code mismatch**
</br>
I added an ingress rule for HTTP on the web instances and I could access the app using the instance public ip but without connection to the ATP database
</br>
After troubleshooting, I found the issue to be in the mushop_api service:

root@mushop-jnkv-0 ~]# systemctl status -l mushop_api
● mushop_api.service - MuShop Basic - API service
   Loaded: loaded (/etc/systemd/system/mushop_api.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2023-04-09 18:04:09 GMT; 24h ago
 Main PID: 12119 (code=exited, status=203/EXEC)

Apr 09 18:04:09 mushop-jnkv-0 systemd[1]: Started MuShop Basic - API service.
Apr 09 18:04:09 mushop-jnkv-0 systemd[1]: mushop_api.service: main process exited, code=exited, status=203/EXEC
Apr 09 18:04:09 mushop-jnkv-0 systemd[1]: Unit mushop_api.service entered failed state.
Apr 09 18:04:09 mushop-jnkv-0 systemd[1]: mushop_api.service failed.

</br>

Further investigation showed the problem to be in the **setup.sh** script:

**Install NodeJs**

- yum -y install oracle-nodejs-release-el7
- yum -y install --disablerepo=ol7_developer_EPEL nodejs

</br>
root@mushop-jnkv-0 ~]#cat setup.log

yum -y install --disablerepo=ol7_developer_EPEL nodejs
Loaded plugins: langpacks, osmsplugin, ulninfo
This system is receiving updates from OSMS.

Error getting repository data for ol7_developer_EPEL, repository not found
</br>

Due to the change of the repo name from **ol7_developer_EPEL** to **ol7_developer_epel-x86_64**, the command installing NodeJs failed, as shown below:

[root@mushop-jnkv-0 ~]# yum repolist ol7_developer_EPEL*
Loaded plugins: langpacks, osmsplugin, ulninfo
This system is receiving updates from OSMS.

**ol7_developer_epel-x86_64**

</br>

This could be resolved by adding an asterisk to the repo name:
yum -y install --disablerepo=ol7_developer_EPEL* nodejs

</br>
Doing so fixed the NodeJs installation and the Load Balancer issue.

**Comment by junior** [comment]
@ahmedmansour5 Looks like you are doing custom installation. 

Using the stack (Here the "magic button" >  [![Deploy MuShop to Oracle Cloud][magic_button]][magic_mushop_basic_stack] ), everything works. The issue is that Oracle decided to remove the Oracle DB Instant Client from yum.oracle.com for aarch64(arm64) shapes for Oracle Linux 7 (Original Image).

If you are doing custom deployment, you need to mitigate this. 

I have planned on the roadmap to update the MuShop basic stack to Oracle Linux 8, which will deploy everything on one click and will restore support for arm64 shapes.

As of today, the MuShop basic stack works (LB working, ADB deployed, Website visible) when you use X86_64 compute shapes.


[magic_button]: https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg
[magic_mushop_basic_stack]: https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://github.com/oracle-quickstart/oci-cloudnative/releases/latest/download/mushop-basic-stack-v2.1.1.zip

**Comment by junior** [comment]
Just tried again. Used the stack, changed to not use always-free resources, select the shape, didn't changed anything else, Run Apply, wait, and was there.
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/551007/231297000-3c5dde16-4731-425e-b88b-a81afa4bc128.png">

<img width="978" alt="image" src="https://user-images.githubusercontent.com/551007/231297066-2525ddb6-02a3-4963-b6d1-540bf4c6bc4e.png">
 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/551007/231297167-dc0b34f3-1542-4a46-9c15-ac0a92c0d448.png">

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/551007/231297239-746f97c8-e915-4a9b-8473-a6a5eaef4668.png">

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/551007/231297681-8d9bb1df-6ad0-4f3e-9cc3-68c4f93d360f.png">

**Comment by junior** [comment]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/551007/231299946-a94ae805-ba12-42e9-9de4-bd57c9569c71.png">

**Comment by ahmedmansour5** [comment]
@junior I followed your steps with the exact variables and parameters, but still getting same issue:

# Step 1 with mushop-basic-stack-latest.zip file from the repo:

<img width="1706" alt="Screen Shot 2023-04-12 at 3 32 54 AM" src="https://user-images.githubusercontent.com/55615740/231324660-baf0feac-022f-485d-bf54-12aae8bf010a.png">

# Step 2 with the defaults as you tried earlier:

<img width="1533" alt="Screen Shot 2023-04-12 at 3 33 33 AM" src="https://user-images.githubusercontent.com/55615740/231324698-1c2c8e88-cf9e-4e1e-a10e-1bc4ae897f9b.png">

# Step 3 uses the same image/shape you are using for the deployment:

<img width="1103" alt="Screen Shot 2023-04-12 at 3 34 00 AM" src="https://user-images.githubusercontent.com/55615740/231324904-860c7342-f118-458b-9278-97ef94c5cc80.png">

# Step 4 uses the default values:

<img width="1126" alt="Screen Shot 2023-04-12 at 3 34 11 AM" src="https://user-images.githubusercontent.com/55615740/231324935-c0c1e6a3-f5da-4216-bae2-7dbc4ffbe81a.png">

# Step 5 here shows the deployment details with the MuShop Basic source code URL:

<img width="1565" alt="Screen Shot 2023-04-12 at 3 38 37 AM" src="https://user-images.githubusercontent.com/55615740/231325805-2b65be34-0db5-4bda-bf6f-b739c86d6e8a.png">


# Step 6 shows the error I keep getting when using the LoadBalancer:

<img width="1056" alt="Screen Shot 2023-04-12 at 3 38 47 AM" src="https://user-images.githubusercontent.com/55615740/231325129-f343ce1b-e6a4-4740-aa2b-6f0e51e76b5a.png">


I am still convinced that the issue here is due to the change of the repo name "**ol7_developer_EPEL**" to "**ol7_developer_epel-x86_64**" during the cloud-init phase in my case.

My proposal for adding an asterisk to the repo name in the setup.template.sh will fix the installation issue with either name (with or without the -x86_64 prefix).

Specifically line 25 in [setup.template.sh](https://github.com/oracle-quickstart/oci-cloudnative/blob/master/deploy/basic/terraform/scripts/setup.template.sh)

\---    yum -y install --disablerepo=ol7_developer_EPEL nodejs
\+++   yum -y install --disablerepo=ol7_developer_EPEL* nodejs

**Comment by junior** [comment]
The only difference is that I got directly from GitHub using the magic button. Did you changed anything on the zip file?

**Comment by junior** [comment]
BTW, as soon everything is deployed, you get 502 from the LB endpoint. The LV need few seconds to become health and start serving

**Comment by ahmedmansour5** [comment]
@junior I deployed both from GitHub using the magic button and from GitHub using the zip file, always the result is the same! I didn't alter anything from any stack (zip or magic button).

As I mentioned earlier, my deployment keeps giving the LB 502 error even after days; I have to manually ssh in the instances and rerun the nodejs installation with an asterisk, after which I restart the mushop_api service and everything works fine.

**Comment by ahmedmansour5** [comment]
## Here are the Load Balancer errors as seen after several hours of the deployment:

<img width="1489" alt="Screen Shot 2023-04-12 at 2 02 22 PM" src="https://user-images.githubusercontent.com/55615740/231451372-c861fbed-ab60-4eb3-b750-892acc6ffa67.png">

## Backend code mismatch error:

<img width="1857" alt="Screen Shot 2023-04-12 at 2 02 45 PM" src="https://user-images.githubusercontent.com/55615740/231451551-13798433-b099-4eac-af1a-f10a323386a2.png">
