### ISSUE TITLE
multiple issues while trying to deploy Complete MuShop with Resource Manager

### ISSUE THREAD

**Issue by shengjun-zh** [oracle-quickstart/oci-cloudnative#404]
![image](https://github.com/oracle-quickstart/oci-cloudnative/assets/31334599/7582b458-a62d-414b-a72d-eff9f1bc3ca1)

**Comment by junior** [comment]
@shengjun-zh you are probably using an old version of the stack. Try to use the latest. All the code was updated to be supported up to Kubernetes 1.31.
