### ISSUE TITLE
Error in applying Terraform job

### ISSUE THREAD

**Issue by yachtsman60** [oracle-quickstart/oci-cloudnative#41]
Getting the following error. Has the VM.Standard.E2.1.Micro been renamed?
oci_core_instance.app-instance.0:` Still creating... (3m10s elapsed)

Error: Error applying plan:
2 errors occurred:
	* oci_core_instance.app-instance[1]: 1 error occurred:
	* oci_core_instance.app-instance.1: Service error:NotAuthorizedOrNotFound. shape VM.Standard.E2.1.Micro not found. http status code: 404. Opc request id: c529dc583f7c911c3f1c3c0bd9ecb748/8DB244F4926340A3149403544EC88ECA/A36BB5A8D4B5071773E45DCC57B3D051
	* oci_core_instance.app-instance[0]: 1 error occurred:
	* oci_core_instance.app-instance.0: Service error:NotAuthorizedOrNotFound. shape VM.Standard.E2.1.Micro not found. http status code: 404. Opc request id: 787c8779d4a55476bf29df6edb7b613c/BD684218CA8C2E14CBD76D3EE430F6A4/0314F6FDD85307FBBAE1FA8D71AFFE8A
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by mvandervliet** [comment]
This is likely because the Always Free eligible (Micro) shapes are not available in the region where the stack was applied. Try switching to the **Home Region** for your tenancy.

**Comment by peterj** [comment]
@yachtsman60 can you confirm if you were able to get past this issue by switching to the Home Region?

**Comment by jeevanjoseph** [comment]
@yachtsman60 bump.

**Comment by jeevanjoseph** [comment]
Closing - please reopen if you are still having issues @yachtsman60

**Comment by palashkulsh** [comment]
for future users facing the same issue, I was facing
```
Error: 404-NotAuthorizedOrNotFound 
│ Provider version: 4.39.0, released on 2021-08-11.  
│ Service: Core Instance 
│ Error Message: shape VM.Standard.A1.Flex not found 
│ OPC request ID: 20535922acb81da7dd8769c262620351/1AC5231BC56B04DEE89B0A5D410437BD/A905AFF249D1F056A85E6CD35003D11B 
│ Suggestion: Either the resource has been deleted or service Core Instance need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
│ 

```

and it was resolved after I removed `baseline_ocpu_utilization = "BASELINE_1_8"` from my instance resource config

**Comment by tsbkw** [comment]
Same issue described by @palashkulsh happen to me, too.
And resolved by the following instruction. 
> and it was resolved after I removed baseline_ocpu_utilization = "BASELINE_1_8" from my instance shape_config for flex instance

AFAIK currently oci support only VM.Standard.E3.Flex shape for burstable instance.
https://docs.oracle.com/en-us/iaas/Content/Compute/References/burstable-instances.htm
