### ISSUE TITLE
Carts API link is broken

### ISSUE THREAD

**Issue by jjspiegel** [oracle-quickstart/oci-cloudnative#46]
src/carts/README.md link to carts api doesn't work:
http://microservices-demo.github.io/api/index?url=https://raw.githubusercontent.com/microservices-demo/carts/master/api-spec/cart.json

**Comment by mvandervliet** [comment]
Thanks @jjspiegel...
👀 @jeevanjoseph

**Comment by jjspiegel** [comment]
The new readme doesn't have this link- closing.
