### ISSUE TITLE
Helm Instructions Error

### ISSUE THREAD

**Issue by jjspiegel** [oracle-quickstart/oci-cloudnative#47]
In these instructions:
https://github.com/oracle-quickstart/oci-cloudnative/blob/master/deploy/complete/helm-chart/README.md

Step 3 gives the following error:

> helm install setup --name mushop-setup --namespace --mushop-setup
Error: unknown flag: --name

> helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Comment by peterj** [comment]
This is probably because you’re using Helm 3 and they’ve changed/reordered parameters to:

helm install [NAME] [CHART] [flags]


You could use: 
helm install mushop-setup setup --namespace --mushop-setup

**Comment by jjspiegel** [comment]
Right, thanks.  I actually had 3 problems with the current instructions.
(1) I had to revert to 2.16 
(2) I had to remove the "--" from the namespace argument
(3) I had to run "helm init --upgrade" since the "tiller" version that was added by oci when I created my cluster was an earlier version (2.14)

This is my first time using Helm so perhaps these things would be obvious to other users.

**Comment by peterj** [comment]
The instructions were written using previous version of Helm. Helm 3 just released a couple of weeks ago. Thanks for reporting this, I’ll make the updates to the readme.

**Comment by peterj** [comment]
Resolve by #49 .
