### ISSUE TITLE
cannot find the Resource Manager

### ISSUE THREAD

**Issue by donhk** [oracle-quickstart/oci-cloudnative#50]
I'm trying to deploy the scripts but I fail to find the Resource Manager, not sure if the GUI changed or something, can you help me out?

the instructions says

Home > Solutions & Platform > Resource Manager > Stacks > Create Stack

there is no "Solutions & Platform"
 
![image](https://user-images.githubusercontent.com/11450292/69770545-07d96e00-114f-11ea-99ca-0280a567c9e9.png)

**Comment by peterj** [comment]
There is a Resource Manager option under the Solutions & Platform header in your screenshot ...

**Comment by donhk** [comment]
thanks!
