### ISSUE TITLE
failure on terraform scripts execution

### ISSUE THREAD

**Issue by donhk** [oracle-quickstart/oci-cloudnative#51]
I run the Terraform scripts and they failed, do I need to do something before

`Terraform Actions > Apply` ?

![image](https://user-images.githubusercontent.com/11450292/69771158-6e5f8b80-1151-11ea-93dc-f042753e9715.png)

[job.log](https://github.com/oracle-quickstart/oci-cloudnative/files/3899500/job.log)

**Comment by peterj** [comment]
Can you confirm you downloaded the zip file from the Releases tab?

**Comment by donhk** [comment]
I clones master, will try again with version v1.0.3, thanks, sorry, I thought they were the same
