### ISSUE TITLE
Docker Compose Module giving error

### ISSUE THREAD

**Issue by aojah1** [oracle-quickstart/oci-cloudnative#66]
I am not able to use the Docker Compose based on the Docker-Compose.yml file. Do you have a working version of the Docker Compose for the MuShop project ?

**Comment by peterj** [comment]
Can you paste the errors you’re seeing/steps your running and that don’t work?

**Comment by aojah1** [comment]
Peter,
Thanks for getting back to me.
This is the exercise I was trying :
oracle-quickstart/oci-cloudnative

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
oracle-quickstart/oci-cloudnative

MuShop - Cloud Native microservices demo for Oracle Cloud Infrastructure - oracle-quickstart/oci-cloudnative
 |

 |

 |






# From this directory
docker-compose up


All the services went into error and I believe it's mostly related to Hibernate library.
24 common frames omitted

orders_1       | Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

orders_1       |  at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]

orders_1       |  at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]

orders_1       |  at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:137) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]

orders_1       |  at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]

orders_1       |  at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:94) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]

orders_1       |  at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]

orders_1       |  ... 41 common frames omitted


Attached is the docker-compose.yml

    On Saturday, January 4, 2020, 09:04:59 PM PST, Peter Jausovec <notifications@github.com> wrote:  
 
 
Can you paste the errors you’re seeing/steps your running and that don’t work?

**Comment by mvandervliet** [comment]
Thanks for reporting this issue. The docker  compose deployment option is not presently functional, with the alternative  being helm/kubernetes. I suggest we leave this issue open, and create a task to resolve.

**Comment by jeevanjoseph** [comment]
The error indicates that the ATP instance is not reachable - which brings us to the issue of documentation - the current docs for using docker compose is bad/non-existent . However you generally have two options here : 
- provision and configure the jdbc url for an ATP instance. Useful if you want to dive in to the java apps and how they connect to atp.
- mock  the service ( The service will internally configure an HSQL dB instance that runs inside the JVM) useful if you don’t care for the java apps themselves but want to focus on the other aspects, and just want the java services to be functional.

**Comment by jeevanjoseph** [comment]
My 2c - The OOTB options for the docker-compose needs to support this plain deployment, mocked services so that users can simply do a docker-compose up and have the whole app be functional, with documentation on how to setup ATP connections per service etc ( for when we start in this task to address this ).

**Comment by jeevanjoseph** [comment]
@aojah1 This should be resolved now with #70 . 
Please let us know !

**Comment by jeevanjoseph** [comment]
Closing - please reopen if you still have issues.
