### ISSUE TITLE
The job failed due to an error in the Terraform configuration.

### ISSUE THREAD

**Issue by mrijpkema** [oracle-quickstart/oci-cloudnative#68]
Hi, 

Tried deploying your application but got this error. Any suggestions?

Initializing provider plugins...
The following providers do not have any version constraints in configuration,
so the latest version was installed.
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.
*provider.oci: version = "~> 3.56"
*provider.random: version = "~> 2.1"
*provider.template: version = "~> 2.1"
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.template_file.mushop: Refreshing state...
data.oci_objectstorage_namespace.user_namespace: Refreshing state...
data.oci_limits_services.test_services: Refreshing state...
data.oci_identity_availability_domains.ADs: Refreshing state...
data.oci_limits_limit_values.test_limit_values[0]: Refreshing state...
data.oci_limits_limit_values.test_limit_values[2]: Refreshing state...
data.oci_limits_limit_values.test_limit_values[1]: Refreshing state...
random_string.autonomous_database_wallet_password: Creating...
random_id.mushop_id: Creating...
random_string.autonomous_database_wallet_password: Creation complete after 0s [id=none]
random_id.mushop_id: Creation complete after 0s [id=_Xw]
oci_database_autonomous_database.mushop_autonomous_database: Creating...
oci_core_virtual_network.mushopVCN: Creating...
oci_identity_policy.mushop_allow_object_storage_lifecycle: Creating...
oci_identity_policy.mushop_allow_object_storage_lifecycle: Creation complete after 0s [id=ocid1.policy.oc1..aaaaaaaax62icbbcsnvj7pr3ibgmbeke5jvlraebnsnm6hn4jx4cu56uujwq]
oci_objectstorage_bucket.mushop: Creating...
oci_core_virtual_network.mushopVCN: Creation complete after 0s [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaebvz6uiau3dtiiln3dvkbrrp4a4bkmfol22epsxwyneobcuiwewq]
oci_objectstorage_bucket.mushop: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892]
oci_core_internet_gateway.mushopIG: Creating...
oci_objectstorage_object.catalogue_sql_script: Creating...
oci_objectstorage_object.entrypoint: Creating...
oci_core_security_list.mushopLBSecurityList: Creating...
oci_objectstorage_object.apache_conf: Creating...
oci_objectstorage_object.mushop_basic: Creating...
oci_objectstorage_object.entrypoint: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/o/entrypoint]
oci_objectstorage_preauthrequest.entrypoint_preauth: Creating...
oci_objectstorage_object.catalogue_sql_script: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/o/catalogue_sql_script]
oci_core_security_list.mushopLBSecurityList: Creation complete after 0s [id=ocid1.securitylist.oc1.eu-frankfurt-1.aaaaaaaahcm3ofqd7trltskqkg6rrlm5xam4wl6s3jurkbevpjv3q6bkib5q]
oci_objectstorage_object.apache_conf: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/o/apache_conf]
oci_objectstorage_preauthrequest.catalogue_sql_script_preauth: Creating...
oci_core_internet_gateway.mushopIG: Creation complete after 0s [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaaziqeedglf2eiaeilnil4vsxxudm6jagpipcfg5xaixibdfb3lb5q]
oci_objectstorage_preauthrequest.apache_conf_preauth: Creating...
oci_core_route_table.mushopLBRT: Creating...
oci_objectstorage_preauthrequest.entrypoint_preauth: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/p/b%2F6XV6GSEP2jNH5JmkidoGuCPY4pvqxp6B77PgYNVwo=:entrypoint]
oci_objectstorage_preauthrequest.catalogue_sql_script_preauth: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/p/Sy7iuCL4Y4%2FckIz8hu104kDATEzQEvCGYGYIcJ%2FR%2F2g=:catalogue_sql_script]
oci_objectstorage_preauthrequest.apache_conf_preauth: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/p/Xu2TpmtBFvgicZBaCIomq3ix86XNw2mOg+UttVrxZxY=:apache_conf]
oci_core_route_table.mushopLBRT: Creation complete after 0s [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaadxho5zwponatlc5jsdcbka7axfxtzmgeecn5qvr33l5rmx2dqrga]
oci_core_subnet.mushopLBSubnet: Creating...
oci_objectstorage_object.mushop_basic: Creation complete after 1s [id=n/fr58n9yubd3p/b/mushop-64892/o/mushop_basic]
oci_objectstorage_preauthrequest.mushop_lite_preauth: Creating...
oci_objectstorage_preauthrequest.mushop_lite_preauth: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/p/seCt8k9741ekjReU8vmFGHr0+DiitYQw3YBm+3tXqeY=:mushop_basic]
oci_core_subnet.mushopLBSubnet: Creation complete after 1s [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaahkfjucxxoiuem3xcruewc4zao6brryiiug2owupzjvkbforcp3iq]
oci_load_balancer_load_balancer.mushop_lb: Creating...
oci_database_autonomous_database.mushop_autonomous_database: Still creating... [10s elapsed]
oci_load_balancer_load_balancer.mushop_lb: Still creating... [10s elapsed]
oci_database_autonomous_database.mushop_autonomous_database: Still creating... [20s elapsed]
oci_load_balancer_load_balancer.mushop_lb: Still creating... [20s elapsed]
oci_database_autonomous_database.mushop_autonomous_database: Still creating... [30s elapsed]
oci_load_balancer_load_balancer.mushop_lb: Still creating... [30s elapsed]
oci_load_balancer_load_balancer.mushop_lb: Creation complete after 33s [id=ocid1.loadbalancer.oc1.eu-frankfurt-1.aaaaaaaa64r33xst3dfx4vb7lsf43nx62fzjmp45co3jwbhbu4tzpnimok6a]
oci_load_balancer_backend_set.mushop-bes: Creating...
oci_database_autonomous_database.mushop_autonomous_database: Still creating... [40s elapsed]
oci_load_balancer_backend_set.mushop-bes: Still creating... [10s elapsed]
oci_load_balancer_backend_set.mushop-bes: Creation complete after 13s [id=loadBalancers/ocid1.loadbalancer.oc1.eu-frankfurt-1.aaaaaaaa64r33xst3dfx4vb7lsf43nx62fzjmp45co3jwbhbu4tzpnimok6a/backendSets/mushop-64892]
oci_load_balancer_listener.mushop_listener: Creating...
oci_database_autonomous_database.mushop_autonomous_database: Still creating... [50s elapsed]
oci_database_autonomous_database.mushop_autonomous_database: Creation complete after 55s [id=ocid1.autonomousdatabase.oc1.eu-frankfurt-1.abtheljtbalf4eizkxygqewuvla5pf6jdfvrhxriuapifqsya5bt5pcg7v4a]
data.oci_database_autonomous_database_wallet.autonomous_database_wallet: Refreshing state...
oci_objectstorage_object.mushop_wallet: Creating...
oci_objectstorage_object.mushop_wallet: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/o/mushop_atp_wallet]
oci_objectstorage_object_lifecycle_policy.mushop_deploy_assets_lifecycle_policy: Creating...
oci_objectstorage_preauthrequest.mushop_wallet_preauth: Creating...
oci_objectstorage_preauthrequest.mushop_wallet_preauth: Creation complete after 0s [id=n/fr58n9yubd3p/b/mushop-64892/p/WSEB%2F3Gi5ZL8%2FOGFXA%2FS8fiejqJ3WqCpQ2HYXFumkGI=:mushop_atp_wallet]
oci_core_instance.app-instance[1]: Creating...
oci_core_instance.app-instance[0]: Creating...
oci_objectstorage_object_lifecycle_policy.mushop_deploy_assets_lifecycle_policy: Creation complete after 1s [id=n/fr58n9yubd3p/b/mushop-64892/l]
oci_load_balancer_listener.mushop_listener: Still creating... [10s elapsed]
oci_core_instance.app-instance[1]: Still creating... [10s elapsed]
oci_core_instance.app-instance[0]: Still creating... [10s elapsed]
oci_load_balancer_listener.mushop_listener: Still creating... [20s elapsed]
oci_load_balancer_listener.mushop_listener: Creation complete after 24s [id=loadBalancers/ocid1.loadbalancer.oc1.eu-frankfurt-1.aaaaaaaa64r33xst3dfx4vb7lsf43nx62fzjmp45co3jwbhbu4tzpnimok6a/listeners/mushop-64892]
oci_core_instance.app-instance[1]: Still creating... [20s elapsed]
oci_core_instance.app-instance[0]: Still creating... [20s elapsed]
oci_core_instance.app-instance[1]: Still creating... [30s elapsed]
oci_core_instance.app-instance[0]: Still creating... [30s elapsed]
oci_core_instance.app-instance[1]: Still creating... [40s elapsed]
oci_core_instance.app-instance[0]: Still creating... [40s elapsed]
oci_core_instance.app-instance[1]: Still creating... [50s elapsed]
oci_core_instance.app-instance[0]: Still creating... [50s elapsed]
oci_core_instance.app-instance[1]: Still creating... [1m0s elapsed]
oci_core_instance.app-instance[0]: Still creating... [1m0s elapsed]
oci_core_instance.app-instance[1]: Still creating... [1m10s elapsed]
oci_core_instance.app-instance[0]: Still creating... [1m10s elapsed]
oci_core_instance.app-instance[1]: Still creating... [1m20s elapsed]
oci_core_instance.app-instance[0]: Still creating... [1m20s elapsed]
oci_core_instance.app-instance[1]: Still creating... [1m30s elapsed]
oci_core_instance.app-instance[0]: Still creating... [1m30s elapsed]
oci_core_instance.app-instance[1]: Still creating... [1m40s elapsed]
oci_core_instance.app-instance[0]: Still creating... [1m40s elapsed]
oci_core_instance.app-instance[1]: Still creating... [1m50s elapsed]
oci_core_instance.app-instance[0]: Still creating... [1m50s elapsed]
oci_core_instance.app-instance[1]: Still creating... [2m0s elapsed]
oci_core_instance.app-instance[0]: Still creating... [2m0s elapsed]
oci_core_instance.app-instance[1]: Still creating... [2m10s elapsed]
oci_core_instance.app-instance[1]: Still creating... [2m20s elapsed]
oci_core_instance.app-instance[1]: Still creating... [2m30s elapsed]
oci_core_instance.app-instance[1]: Still creating... [2m40s elapsed]
oci_core_instance.app-instance[1]: Still creating... [2m50s elapsed]
oci_core_instance.app-instance[1]: Still creating... [3m0s elapsed]
Error: Service error:InternalError. Out of host capacity.. http status code: 500. Opc request id: f580929d0dd07dadde36fc8508b38b3b/9E05436E8425F12F32E6CEC4FD857D4F/C0AB1280319A0D28172E4D2C0BB26EC5
  on main.tf line 11, in resource "oci_core_instance"" ""app-instance" 
  11: resource "oci_core_instance"" ""app-instance" {
Error: Service error:InternalError. Out of host capacity.. http status code: 500. Opc request id: 712eee62fb9b414acb01cf017c1e323e/AC18E3B5782DD3447D118FAB9A15148B/15BB437E30AD0E5F88DBDE43E7BDF523
  on main.tf line 11, in resource "oci_core_instance"" ""app-instance" 
  11: resource "oci_core_instance"" ""app-instance" {

Regards,
Martijn
[ocid1.ormjob.oc1.eu-frankfurt-1.aaaaaaaak23cfmvvt7uztx7nxrhg7scs6dmf7c5a7tqv2ohpsz4iboouzdqa.log](https://github.com/oracle-quickstart/oci-cloudnative/files/4041441/ocid1.ormjob.oc1.eu-frankfurt-1.aaaaaaaak23cfmvvt7uztx7nxrhg7scs6dmf7c5a7tqv2ohpsz4iboouzdqa.log)

**Comment by jeevanjoseph** [comment]
@mrijpkema - this seems like a compute capacity issue in Frankfurt. 
This stack uses the Always Free "micro" shaped instances which sometimes are not available depending on the region (although this is usually addressed quickly). I can suggest two things here. 

- Try a different region if you have access to another region. This is localized to a region.
- Wait for a bit and try again, as capacity issues are resolved quickly.

You can also switch to a paid instance shape, which have SLA's and guaranteed availability. This will require you to change the shape of the instance - [see here](https://github.com/oracle-quickstart/oci-cloudnative/blob/0c66c23228cdfe8262ce2da1bf4b0e5d37f6a7ee/deploy/basic/terraform/main.tf#L66) and check [this to rebuild the stack](https://github.com/oracle-quickstart/oci-cloudnative/tree/master/deploy/basic#build)

**Comment by mrijpkema** [comment]
Hi Jeevan,
I tried today and it works
Thanks!
