### ISSUE TITLE
Basic vs Complete - Database interaction

### ISSUE THREAD

**Issue by bobpender** [oracle-quickstart/oci-cloudnative#78]
I installed the Basic.  The website looked good.  I don't know what functions are supposed to actually work.  I looked in the database and did not see the schemas that seem to be created in some of the .sql files I see.  Do I need to install the complete for database interaction? I cloned the Github repository. Is it the same repository for both Basic and Complete?  I wanted to understand the simplest way to deploy a web/mobile app and interact with the database.  With the Basic, I don't see that, or I did something wrong. I have not been a developer for a while (Oracle DBA for 35+ years) but would like to dabble. What IDE was used for this project? I assume the directory structure in Github corresponds to something built by an IDE.

**Comment by jeevanjoseph** [comment]
Hi @bobpender 

Mushop Basic is different from the Complete version, in that the basic deployment configuration uses a single database instance - for the catalogue service. The other services are mocked/stubbed to meet the footprint of the "Always Free" resources (these never expire, even after your trial and $300 credit does). So the schema you would find in your ATP instance is  `catalogue_user` and it would be seeded with some product data that the UI displays. The other schemas are not installed or used in the Basic version. The schema is setup as part of  the terraform deploy, via cloud-init - https://github.com/oracle-quickstart/oci-cloudnative/blob/a9a3ce42f40bfbbfc3192f4fe6c05be91b4ff9f2/deploy/basic/terraform/scripts/node.sh#L62 


Both the Complete and Basic versions use the __same source code__ and are built the same way, resulting in the very same binary artifacts after build. The difference is how we deploy them. In the spirit of [12factor applications](https://www.12factor.net/), these are designed to have external configuration. So **Complete** and **Basic** are deployment configurations, not two separate code bases.

You should be able to interact with the DB using basic. Once you have it deployed, you should see an ATP instance in your tenancy(it will in the same compartment that you chose, when deploying the stack - root compartment by default). This instance is seeded with the `catalogue_user `schema. You can connect to the ATP instance as `ADMIN` user or as the `catalogue_user`. The `ADMIN` password is generated and is shown to you after you deploy the stack. You can see this in the **Application Information** Tab or the ** Log window** that shows the output of the Terraform Apply , and should look something like whats shown [here](https://github.com/oracle-quickstart/oci-cloudnative/blob/master/README.md#getting-started-with-mushop-basic) at the very end of the output. Take a look at the [script](https://github.com/oracle-quickstart/oci-cloudnative/blob/a9a3ce42f40bfbbfc3192f4fe6c05be91b4ff9f2/src/catalogue/dbdata/atp_mushop_catalogue.sql#L7) for the catalogue service to see how to connect as `catalogue_user` ( yep, we will change that ! )
If you need help with connecting your favorite tool(SQL*Plus, SQL Developer, TOAD etc.) to the ATP database, take a look [here](https://docs.oracle.com/en/cloud/paas/atp-cloud/atpug/connect-intorduction.html#GUID-CD4C10A6-1C1E-4969-8F67-1433B6CE626A). You can also try the [SQL developer web](https://blogs.oracle.com/developers/sql-developer-web-now-available-for-oracle-autonomous-database)

We don't really __need__ an IDE for this, and we don't use a "standard" among ourselves. Everyone in our team has their own preferences and workflows with our respective tools of choice. A text editor with some good editing capabilities is all that is required. A lot of us use `vi` (with some plugins of course) and [visual  studio code](https://code.visualstudio.com/), and others include [atom](https://atom.io/), and [sublime text](https://www.sublimetext.com/). The structure is what we decided on, not generated by an ide. It roughly translates to a `/src` for the source code for the application and test cases, including the build files for each application/service. This is just standard practice. The only other directory of consequence is `/deploy` that captures the various deployment models that the application can be deployed in. We generally use the [12factor](https://www.12factor.net/) application principles to make sure that deployment configuration does not creep in to source code, and vice versa. 

Let us know if you are still having issue connecting to the database and exploring, we'd be happy to help !

**Comment by bobpender** [comment]
I destroyed the stack, because I thought I would have to use complete but
now I think I will deploy basic again.
I am sure the catalogue_user was not in that database.  I was connected to
the database created by the deploy, there must have been an error in the
deploy.
Let me try it again and see.
Thanks for the thorough response.

**Comment by jeevanjoseph** [comment]
@bobpender - were you able to provision it and see the database interactions ?

**Comment by bobpender** [comment]
I have been busy.  I will get back to it soon.

**Comment by jeevanjoseph** [comment]
@bobpender  - Closing, please reopen if you still need to identify the database schemas.
