### ISSUE TITLE
resource manager issue when terraform plan

### ISSUE THREAD

**Issue by davinwei2017** [oracle-quickstart/oci-cloudnative#95]
when i used OCI resource manager to do terraform plan, i got the following error message, any suggestion to fix it ? thanks
Initializing provider plugins...
The following providers do not have any version constraints in configuration,
so the latest version was installed.
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.
*provider.oci: version = "~> 3.61"
*provider.random: version = "~> 2.1"
*provider.template: version = "~> 2.1"
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
data.template_file.mushop: Refreshing state...
data.oci_objectstorage_namespace.user_namespace: Refreshing state...
data.oci_identity_availability_domains.ADs: Refreshing state...
data.oci_limits_services.test_services: Refreshing state...
Warning: Quoted references are deprecated
  on storage.tf line 11, in resource "oci_objectstorage_bucket"" ""mushop" 
  11:   depends_on = ["oci_identity_policy.mushop_allow_object_storage_lifecycle"]
In this context, references are expected literally rather than in quotes.
Terraform 0.11 and earlier required quotes, but quoted references are now
deprecated and will be removed in a future version of Terraform. Remove the
quotes surrounding this reference to silence this warning.
(and 2 more similar warnings elsewhere)
Error: Attempt to index null value
  on datasources.tf line 57, in data "oci_limits_limit_values"" ""test_limit_values" 
  57:   service_name   = data.oci_limits_services.test_services.services.0.name
    |----------------
    | data.oci_limits_services.test_services.services is null
This value is null, so it does not have any indices.

**Comment by jeevanjoseph** [comment]
@davinwei2017 - do you have access to “always-free” resources ? Can you confirm that you are doing this from a trial that you personally signed up for or a public tenancy?

**Comment by davinwei2017** [comment]
> @davinwei2017 - do you have access to “always-free” resources ? Can you confirm that you are doing this from a trial that you personally signed up for or a public tenancy?

I used public tenancy

**Comment by jeevanjoseph** [comment]
@davinwei2017 - 
- Are you trying to provision this on the home region for your tenancy ?
- Can you try to provision an micro shape compute instance through the console ? (Create compute instance > Change Shape > Select "VM.Standard.E2.1.Micro"  as the shape)

Can you see if that shape is an option for you ?
This stack is developed for targeting only Always Free resources (you can change them obviously - see instructions on [customizing the stack](https://github.com/oracle-quickstart/oci-cloudnative/tree/master/deploy/basic#build) ). More info on Free Tier (micro shapes) are available [here](https://docs.cloud.oracle.com/en-us/iaas/Content/FreeTier/resourceref.htm)

**Comment by davinwei2017** [comment]
> @davinwei2017 -
> 
> * Are you trying to provision this on the home region for your tenancy ? (the region drop down in the console will show the home region).
> * Can you try to provision an micro shape compute instance through the console ? (Create compute instance > Change Shape > Select "VM.Standard.E2.1.Micro"  as the shape)
> 
> Can you see if that shape is an option for you ?
> This stack is developed for targeting only Always Free resources (you can change them obviously - see instructions on [customizing the stack](https://github.com/oracle-quickstart/oci-cloudnative/tree/master/deploy/basic#build) ). More info on Free Tier (micro shapes) are available [here](https://docs.cloud.oracle.com/en-us/iaas/Content/FreeTier/resourceref.htm)

i customizing the stack with following. 
 instance_shape = "VM.Standard2.1"
 lb_shape = "100Mbps"
and created one new zip file and uploaded it. but when i executed the terraform plan, and got following issues:
ata.template_file.mushop: Refreshing state...
data.oci_limits_services.test_services: Refreshing state...
data.oci_identity_availability_domains.ADs: Refreshing state...
data.oci_objectstorage_namespace.user_namespace: Refreshing state...
Error: Attempt to index null value
  on datasources.tf line 57, in data "oci_limits_limit_values"" ""test_limit_values" 
  57:   service_name   = data.oci_limits_services.test_services.services.0.name
    |----------------
    | data.oci_limits_services.test_services.services is null
This value is null, so it does not have any indices.

**Comment by jeevanjoseph** [comment]
@davinwei2017 - when changing the shape you would also want to remove the logic to determine the free tier availability domains and make that a variable too. Basically - [replacing this line](https://github.com/oracle-quickstart/oci-cloudnative/blob/158ab9ff64dfdf3ef252605d0b4003bbb95ed7a3/deploy/basic/terraform/main.tf#L69) with a variable or a constant.

**Comment by jeevanjoseph** [comment]
@davinwei2017 were you able to customize the stack for non-free instances ?

**Comment by davinwei2017** [comment]
> @davinwei2017 were you able to customize the stack for non-free instances ?

don't know how to set  availability_domain value for non-free instances. welcome your comments

**Comment by junior** [comment]
> > @davinwei2017 were you able to customize the stack for non-free instances ?
> 
> don't know how to set availability_domain value for non-free instances. welcome your comments

You do not need to set the availability domain, you just need to change the shape to one that you have capacity. There's a terraform expression that will test the shape against all possible ads to see if there's capacity.

**Comment by davinwei2017** [comment]
> > > @davinwei2017 were you able to customize the stack for non-free instances ?
> > 
> > 
> > don't know how to set availability_domain value for non-free instances. welcome your comments
> 
> You do not need to set the availability domain, you just need to change the shape to one that you have capacity. There's a terraform expression that will test the shape against all possible ads to see if there's capacity.

i only set the VM shape and LBR shape and re-package and upload it and i failed to  do terraform plan.  can you give a guide for non-free trial account ? thanks

**Comment by jeevanjoseph** [comment]
@davinwei2017 - the complete stack is now available though a terraform configuration. #153 implements this and is now available. All non-free shapes are supported, as the deployment is done on top of a kubernetes cluster (which the stack will create for you.)

**Comment by jeevanjoseph** [comment]
Closing - please feel to reopen if you need further assistance.
